In [8]:
import pandas as pd
import ast
import numpy as np

from sleeper.api import get_user
from sleeper.api import (
    get_draft,
    get_drafts_in_league,
    get_player_draft_picks,
    get_traded_draft_picks,
    get_user_drafts_for_year,
)
from sleeper.api import (
    get_league,
    get_losers_bracket,
    get_matchups_for_week,
    get_rosters,
    get_sport_state,
    get_traded_picks,
    get_transactions,
    get_user_leagues_for_year,
    get_users_in_league,
    get_winners_bracket,
    get_all_players
)

In [4]:
nfl_players = get_all_players(sport="nfl")
players = pd.DataFrame(nfl_players)
players = players.T

In [14]:
from sleeper.api import get_user

if __name__ == "__main__":
    # get a user by username
    user_1 = get_user(identifier="1130199303684915200")
user_1

{'avatar': 'b319fdf8b7b5b0359d3c78622ba4d70c',
 'cookies': None,
 'created': None,
 'currencies': None,
 'data_updated': None,
 'deleted': None,
 'display_name': 'manu1016',
 'email': None,
 'is_bot': False,
 'metadata': None,
 'notifications': None,
 'pending': None,
 'phone': None,
 'real_name': None,
 'solicitable': None,
 'summoner_name': None,
 'summoner_region': None,
 'token': None,
 'user_id': '1130199303684915200',
 'username': 'manu1016',
 'verification': None}

In [90]:
from sleeper.api import (
    get_draft,
    get_drafts_in_league,
    get_player_draft_picks,
    get_traded_draft_picks,
    get_user_drafts_for_year,
)

if __name__ == "__main__":
    # get all drafts that a user was in for a year
    # NO SIRVE AS OF DEC 2025 PORQUE SLEEPER CAMBIO YEAR A SEASON EN EL API, 2024 si sirve pero no 2025
    # user_drafts = get_user_drafts_for_year(user_id="1130199303684915200", sport="nfl", year= 2025)

    # get all drafts for a league
    league_drafts = get_drafts_in_league(league_id="1180092461749104640")

    # get a draft by its ID
    draft = get_draft(draft_id="1180092461749104641")

    # get all draft picks for a draft
    draft_picks = get_player_draft_picks(
        draft_id="1180092461749104641")

In [86]:
# get_user_leagues_for_year(user_id=1130199303684915200, sport="nfl",year=2025 )

[{'loser_bracket_id': 1304398335200731136,
  'previous_league_id': None,
  'last_author_is_bot': True,
  'season_type': 'regular',
  'bracket_overrides_id': None,
  'avatar': '6338a635baad4ea49c33ea111b6bdaf3',
  'last_transaction_id': 1285803165752516608,
  'league_id': '1181670620751540224',
  'metadata': {'auto_continue': 'on',
   'continued': 'yes',
   'copy_from_league_id': '1130199667238621184',
   'keeper_deadline': '0',
   'trophy_loser': 'loser4',
   'trophy_loser_background': 'fly',
   'trophy_loser_banner_text': 'EL CAMPEON DE LAS PERRAS',
   'trophy_winner': 'winner4',
   'trophy_winner_background': 'fireworks',
   'trophy_winner_banner_text': 'BALL KNOWER'},
  'loser_bracket_overrides_id': None,
  'settings': {'best_ball': 0,
   'last_report': 14,
   'waiver_budget': 100,
   'disable_adds': 0,
   'divisions': 0,
   'capacity_override': 0,
   'waiver_bid_min': 0,
   'taxi_deadline': 0,
   'draft_rounds': 4,
   'reserve_allow_na': 0,
   'start_week': 1,
   'playoff_seed_type': 0,
   'playoff_teams': 6,
   'veto_votes_needed': 6,
   'num_teams': 10,
   'daily_waivers_hour': 0,
   'playoff_type': 1,
   'taxi_slots': 5,
   'sub_start_time_eligibility': 0,
   'last_scored_leg': 16,
   'daily_waivers_days': 5461,
   'sub_lock_if_starter_active': 0,
   'playoff_week_start': 15,
   'position_limit_k': 2,
   'waiver_clear_days': 1,
   'reserve_allow_doubtful': 0,
   'commissioner_direct_invite': 0,
   'veto_auto_poll': 1,
   'reserve_allow_dnr': 0,
   'taxi_allow_vets': 1,
   'waiver_day_of_week': 2,
   'playoff_round_type': 0,
   'reserve_allow_out': 0,
   'reserve_allow_sus': 1,
   'veto_show_votes': 0,
   'trade_deadline': 99,
   'taxi_years': 2,
   'daily_waivers': 0,
   'faab_suggestions': 0,
   'position_limit_def': 2,
   'disable_trades': 0,
   'pick_trading': 1,
   'type': 2,
   'max_keepers': 1,
   'waiver_type': 1,
   'max_subs': 3,
   'league_average_match': 0,
   'trade_review_days': 1,
   'bench_lock': 0,
   'offseason_adds': 0,
   'leg': 17,
   'reserve_slots': 10,
   'reserve_allow_cov': 1,
   'daily_waivers_last_ran': 20},
  'last_message_time': 1766710491013,
  'draft_id': '1181670621661540352',
  'sport': 'nfl',
  'group_id': None,
  'status': 'post_season',
  'company_id': None,
  'display_order': 0,
  'last_author_avatar': None,
  'last_author_display_name': 'sys',
  'name': 'Saint Paul Dynasty NFL',
  'scoring_settings': {'sack': 1.0,
   'fgm_40_49': 4.0,
   'bonus_rec_te': 0.5,
   'pass_int': -2.0,
   'pts_allow_0': 10.0,
   'pass_2pt': 2.0,
   'st_td': 6.0,
   'rec_td': 6.0,
   'fgm_30_39': 3.0,
   'fgm_50_59': 5.0,
   'xpmiss': 0.0,
   'rush_td': 6.0,
   'rec_2pt': 2.0,
   'st_fum_rec': 2.0,
   'fgmiss': 0.0,
   'ff': 2.0,
   'rec': 1.0,
   'pts_allow_14_20': 1.0,
   'def_2pt': 2.0,
   'fgm_0_19': 3.0,
   'int': 2.0,
   'def_st_fum_rec': 2.0,
   'fum_lost': -2.0,
   'pts_allow_1_6': 7.0,
   'fgm_60p': 6.0,
   'fgm_20_29': 3.0,
   'pts_allow_21_27': 0.0,
   'xpm': 1.0,
   'rush_2pt': 2.0,
   'fum_rec': 2.0,
   'def_st_td': 6.0,
   'fgm_50p': 0.0,
   'def_td': 6.0,
   'safe': 2.0,
   'pass_yd': 0.04,
   'blk_kick': 2.0,
   'pass_td': 6.0,
   'rush_yd': 0.1,
   'fum': 0.0,
   'pts_allow_28_34': -1.0,
   'pts_allow_35p': -4.0,
   'fum_rec_td': 6.0,
   'rec_yd': 0.1,
   'def_st_ff': 2.0,
   'pts_allow_7_13': 4.0,
   'st_ff': 2.0},
  'shard': 368,
  'bracket_id': 1304398335196536832,
  'total_rosters': 10,
  'last_message_id': '1310082389086605312',
  'last_message_attachment': None,
  'roster_positions': ['QB',
   'RB',
   'RB',
   'WR',
   'WR',
   'TE',
   'FLEX',
   'FLEX',
   'FLEX',
   'SUPER_FLEX',
   'K',
   'DEF',
   'BN',
   'BN',
   'BN',
   'BN',
   'BN',
   'BN',
   'BN',
   'BN',
   'BN',
   'BN',
   'BN',
   'BN',
   'BN',
   'BN',
   'BN'],
  'season': '2025',
  'last_read_id': '1310082389086605312',
  'last_message_text_map': None,
  'last_author_id': '166666666666666666',
  'last_pinned_message_id': '1302177791294345216'},
 {'loser_bracket_id': 1304405236886036480,
  'previous_league_id': '1130199667238621184',
  'last_author_is_bot': True,
  'season_type': 'regular',
  'bracket_overrides_id': None,
  'avatar': '6338a635baad4ea49c33ea111b6bdaf3',
  'last_transaction_id': 1290062703129292800,
  'league_id': '1180092461749104640',
  'metadata': {'auto_continue': 'on',
   'keeper_deadline': '0',
   'latest_league_winner_roster_id': '1'},
  'loser_bracket_overrides_id': None,
  'settings': {'best_ball': 0,
   'last_report': 14,
   'waiver_budget': 100,
   'disable_adds': 0,
   'divisions': 0,
   'capacity_override': 0,
   'waiver_bid_min': 0,
   'taxi_deadline': 0,
   'draft_rounds': 3,
   'reserve_allow_na': 0,
   'start_week': 1,
   'playoff_seed_type': 0,
   'playoff_teams': 6,
   'veto_votes_needed': 6,
   'num_teams': 10,
   'daily_waivers_hour': 0,
   'playoff_type': 1,
   'taxi_slots': 0,
   'sub_start_time_eligibility': 0,
   'last_scored_leg': 16,
   'daily_waivers_days': 5461,
   'sub_lock_if_starter_active': 0,
   'playoff_week_start': 15,
   'waiver_clear_days': 1,
   'reserve_allow_doubtful': 0,
   'commissioner_direct_invite': 0,
   'veto_auto_poll': 1,
   'reserve_allow_dnr': 0,
   'taxi_allow_vets': 0,
   'waiver_day_of_week': 2,
   'playoff_round_type': 0,
   'reserve_allow_out': 0,
   'reserve_allow_sus': 1,
   'veto_show_votes': 0,
   'trade_deadline': 14,
   'taxi_years': 0,
   'daily_waivers': 0,
   'faab_suggestions': 0,
   'disable_trades': 0,
   'pick_trading': 1,
   'type': 0,
   'max_keepers': 1,
   'waiver_type': 1,
   'max_subs': 2,
   'league_average_match': 0,
   'trade_review_days': 1,
   'bench_lock': 0,
   'offseason_adds': 0,
   'leg': 17,
   'reserve_slots': 4,
   'reserve_allow_cov': 1,
   'daily_waivers_last_ran': 23},
  'last_message_time': 1766696522313,
  'draft_id': '1180092461749104641',
  'sport': 'nfl',
  'group_id': None,
  'status': 'post_season',
  'company_id': None,
  'display_order': 0,
  'last_author_avatar': None,
  'last_author_display_name': 'sys',
  'name': 'Saint Paul NFL',
  'scoring_settings': {'sack': 1.0,
   'fgm_40_49': 4.0,
   'pass_int': -2.0,
   'pts_allow_0': 10.0,
   'pass_2pt': 2.0,
   'st_td': 6.0,
   'rec_td': 6.0,
   'fgm_30_39': 3.0,
   'fgm_50_59': 5.0,
   'xpmiss': 0.0,
   'rush_td': 6.0,
   'rec_2pt': 2.0,
   'st_fum_rec': 2.0,
   'fgmiss': 0.0,
   'ff': 2.0,
   'rec': 1.0,
   'pts_allow_14_20': 1.0,
   'def_2pt': 2.0,
   'fgm_0_19': 3.0,
   'int': 2.0,
   'def_st_fum_rec': 2.0,
   'fum_lost': -2.0,
   'pts_allow_1_6': 7.0,
   'fgm_60p': 6.0,
   'fgm_20_29': 3.0,
   'pts_allow_21_27': 0.0,
   'xpm': 1.0,
   'rush_2pt': 2.0,
   'fum_rec': 2.0,
   'def_st_td': 6.0,
   'fgm_50p': 0.0,
   'def_td': 6.0,
   'safe': 2.0,
   'pass_yd': 0.04,
   'blk_kick': 2.0,
   'pass_td': 4.0,
   'rush_yd': 0.1,
   'fum': 0.0,
   'pts_allow_28_34': -1.0,
   'pts_allow_35p': -4.0,
   'fum_rec_td': 6.0,
   'rec_yd': 0.1,
   'def_st_ff': 2.0,
   'pts_allow_7_13': 4.0,
   'st_ff': 2.0},
  'shard': 831,
  'bracket_id': 1304405236881842176,
  'total_rosters': 10,
  'last_message_id': '1310023800112312320',
  'last_message_attachment': None,
  'roster_positions': ['QB',
   'RB',
   'RB',
   'WR',
   'WR',
   'TE',
   'FLEX',
   'FLEX',
   'K',
   'DEF',
   'BN',
   'BN',
   'BN',
   'BN',
   'BN',
   'BN'],
  'season': '2025',
  'last_read_id': '1310023800112312320',
  'last_message_text_map': None,
  'last_author_id': '166666666666666666',
  'last_pinned_message_id': '1293828141185236992'}]

In [94]:
import pandas as pd
import ast

sanpol2 = pd.DataFrame(draft_picks)
sanpol2.drop(columns=['draft_id','is_keeper'], inplace=True)
sanpol2['metadata'] = sanpol2['metadata'].astype(str)

In [96]:
usuarios = []
for i in range(10):
    usuarios.append(sanpol2['picked_by'].iloc[i])

In [98]:
from sleeper.api import get_user
users2 = []
if __name__ == "__main__":
    for i in usuarios:
        users2.append(get_user(identifier=i))

In [102]:
users3 = ['manu1016','alejandrovargas3000', 'profeceltic', 'mtamayo21', 'frrankthetank', 'thejahater' , 'badillad03', 'mmonge2', 'miquev','sebasvindas']
users4 = [1130199303684915200, 1150198110141026304, 1130319313522704384, 1130211805168689152, 1130203918862192640, 1125596889426063360, 1104293144230813696, 1130210372142706688, 976970448661524480, 1130428971469991936]
users5 = [1,9,8,7,4,5,2,6,3,10]

# users3 = ['badillad03','mtamayo21', 'davidloaiza','tvargasr','grdcr','crbroncos','marspowers','dansab16','viaud326','obejota2001','dariengc','mantofer02']
# users4 = [1104293144230813696, 1130211805168689152, 1130244177901645824,1137258192351698944,1137604548329316352,1253399679454937088,1258823236498489344,1268658421729611776,991136315552915456,992121207313006592,992148608550027264,994693654587531264]
# users5 = [8,11,9,3,2,4,10,5,1,7,12,6]

In [104]:
datos = pd.DataFrame(sanpol2['metadata'])
datos = datos.join(datos['metadata'].str.split(',', expand=True))
datos.drop(columns=['metadata',1,3,4,5,7,8,10,11], inplace=True)
datos2 = []
for col in datos.columns:
    datos[col]=datos[col].astype(str)
    datos2.append(datos[col].str.split(':', expand=True))
datos.rename({0: 'a', 2: 'b', 6:'c' , 9:'d', 12: 'e'}, axis=1, inplace=True)
datos3 = []
for col in range(len(datos2)):
    datos3.append(pd.DataFrame(datos2[col][1]))
for i in range(len(datos3)):
    datos[i]=datos3[i]
datos.drop(columns=['a', 'b', 'c', 'd', 'e'], inplace=True)
for i in datos.columns:
    datos[i] = datos[i].str.replace("'", '')
    datos[i] = datos[i].str.replace('"', '')
    datos[i] = datos[i].str.replace('}', '')
datos.insert(4, "f", 'Year:')
datos.insert(4, 'four', datos['f'] + '' + datos[4])
datos.drop(columns=['f',4], inplace=True)
datos.rename({'four':4}, axis=1, inplace=True)
datos.insert(0, 'four', datos[0] + '' + datos[1])
datos.drop(columns=[0,1], inplace=True)
datos.rename({'four':0, 2:1,3:2, 4:3}, axis=1, inplace=True)

In [110]:
sanpol = pd.concat([sanpol2, datos], axis=1)
sanpol.drop(columns=['metadata','player_id','reactions','roster_id','draft_slot'],inplace=True)
sanpol['picked_by' ] = sanpol['picked_by'].astype(float)
sanpol.replace({'picked_by': {1130199303684915200:'manu1016',
  1150198110141026304:'alejandrovargas3000',
  1130319313522704384:'profeceltic',
  1130211805168689152:'mtamayo21',
  1130203918862192640:'frrankthetank',
  1125596889426063360:'thejahater',
  1104293144230813696:'badillad03',
  1130210372142706688:'mmonge2',
  976970448661524480:'miquev',
  1130428971469991936:'sebasvindas'}},inplace=True)

# sanpol.replace({'picked_by': {1104293144230813696: 'badillad03',
#                              1130211805168689152: 'mtamayo21',
#                              1130244177901645824: 'davidloaiza',
#                              1137258192351698944: 'tvargasr',
#                              1137604548329316352: 'grdcr',
#                              1253399679454937088: 'crbroncos',
#                              1258823236498489344: 'marspowers',
#                              1268658421729611776: 'dansab16',
#                              991136315552915456: 'viaud326',
#                              992121207313006592: 'obejota2001',
#                              992148608550027264: 'dariengc',
#                              994693654587531264: 'mantofer02'}},inplace=True)

sanpol = sanpol.reindex(columns=['round','pick_no', 'picked_by',0,1,2,3])
sanpol.rename({'round':'Round','pick_no':'Pick','picked_by':'Picked by',0:'Name',1:'Position',2:'Team',3:'Experience'}, axis=1, inplace=True)

In [74]:
 sanpol.to_excel("draft.xlsx",index=False)

In [751]:
players.loc['MIN']

fantasy_positions             [DEF]
high_school                     NaN
search_first_name               NaN
injury_status                  None
team_changed_at                 NaN
pandascore_id                   NaN
practice_description            NaN
last_name                   Vikings
injury_body_part                NaN
metadata                        NaN
active                         True
oddsjam_id                      NaN
player_shard                    NaN
birth_state                     NaN
birth_city                      NaN
fantasy_data_id                 NaN
weight                          NaN
age                             NaN
hashtag                         NaN
first_name                Minnesota
team                            MIN
status                          NaN
birth_country                   NaN
competitions                    NaN
college                         NaN
swish_id                        NaN
search_full_name                NaN
rotowire_id                     NaN
sport                           nfl
search_rank                     NaN
opta_id                         NaN
sportradar_id                   NaN
injury_start_date               NaN
team_abbr                       NaN
birth_date                      NaN
search_last_name                NaN
height                          NaN
gsis_id                         NaN
stats_id                        NaN
full_name                       NaN
depth_chart_position            NaN
rotoworld_id                    NaN
espn_id                         NaN
news_updated                    NaN
position                        DEF
injury_notes                    NaN
kalshi_id                       NaN
player_id                       MIN
years_exp                       NaN
yahoo_id                        NaN
depth_chart_order               NaN
practice_participation          NaN
number                          NaN
Name: MIN, dtype: object

In [156]:
# Retrieves all weeks' transactions, placing them in a list
transactions = []
for i in range(18):
     transactions.append(get_transactions(league_id=1180092461749104640, week=i))
# Creates a DataFrame for each week's moves
moves = pd.DataFrame(transactions)
moves = moves.T
moves.drop(columns=[0], inplace=True)
# Separating nontrades from trades for all weeks
nontrades = []
for i in moves:
    nontrades.append(moves[i].astype(str).str.split("'",expand=True))

In [601]:
# THIS IS JUST WAIVERS FOR NOW
# Separating the three types of nontrades from one another

waiver_adds_index = []
waiver_adds = []

# Creates indexes for first 16 weeks, for loop doesnt work because it gives a python index error

i = 0
while i in range(16):
    waiver_adds_index.append((nontrades[i][7].values == 'waiver').copy())
    i+=1

# Creates dataframes for first 16 weeks, for loop doesnt work because it gives a python index error

k = 0
while k in range(16):
    waiver_adds.append(pd.DataFrame(nontrades[k].values[waiver_adds_index[k]], nontrades[k].index[waiver_adds_index[k]], nontrades[k].columns))
    k+=1

# Separating 3 types of notes obtained

waivers_failed_type1_index = []
waivers_failed_type1 = []

waivers_failed_type2_index = []
waivers_failed_type2 = []

waivers_success_index = []
waivers_success = []

n = 0
while n in range(16):
    waivers_failed_type1_index.append((waiver_adds[n][13].values == 'Unfortunately, your roster will have too many players after this transaction.').copy())
    waivers_failed_type2_index.append((waiver_adds[n][13].values == 'This player was claimed by another owner.').copy())
    waivers_success_index.append((waiver_adds[n][13].values == 'Your waiver claim was processed successfully!').copy())
    n+=1

# Creating new waivers failed dataframe

waivers_failed = []

m = 0
while m in range(16):
    waivers_failed_type1.append(pd.DataFrame(waiver_adds[m].values[waivers_failed_type1_index[m]], waiver_adds[m].index[waivers_failed_type1_index[m]], waiver_adds[m].columns))
    waivers_failed_type2.append(pd.DataFrame(waiver_adds[m].values[waivers_failed_type2_index[m]], waiver_adds[m].index[waivers_failed_type2_index[m]], waiver_adds[m].columns))
    waivers_success.append(pd.DataFrame(waiver_adds[m].values[waivers_success_index[m]], waiver_adds[m].index[waivers_success_index[m]], waiver_adds[m].columns))
    waivers_failed.append(pd.concat([waivers_failed_type1[m],waivers_failed_type2[m]], axis=0))
    waivers_failed[m].sort_index(inplace=True)
    m+=1

# Separating failed waivers by multidrop of players or single drop

waivers_failed_priority_index = []
waivers_failed_priority = []

waivers_failed_nopriority_index = []
waivers_failed_nopriority = []

p = 0
while p in range(16):
    waivers_failed_priority_index.append((waivers_failed[p][19].values == 'priority').copy())
    waivers_failed_nopriority_index.append((waivers_failed[p][19].values == 'seq').copy())
    p+=1

q = 0
while q in range(16):
    waivers_failed_priority.append(pd.DataFrame(waivers_failed[q].values[waivers_failed_priority_index[q]], waivers_failed[q].index[waivers_failed_priority_index[q]], waivers_failed[q].columns))
    waivers_failed_nopriority.append(pd.DataFrame(waivers_failed[q].values[waivers_failed_nopriority_index[q]], waivers_failed[q].index[waivers_failed_nopriority_index[q]], waivers_failed[q].columns))
    waivers_failed_nopriority[q].insert(19, "a", np.nan)
    waivers_failed_nopriority[q].insert(19, "b", np.nan)
    waivers_failed_nopriority[q].columns = range(waivers_failed_nopriority[q].columns.size)
    q+=1

# fixing discrepancy between priority and no priority for failed

if len(waivers_failed) == len(waivers_failed_nopriority):
    for i in range(len(waivers_failed)):
        waivers_failed[i].update(waivers_failed_nopriority[i])

waivers_failed_nodrop_index = []
waivers_failed_nodrop = []

waivers_failed_drop_index = []
waivers_failed_drop = []

# doing the same thing for drop or no drop of player

g = 0
while g in range(16):
    waivers_failed_nodrop_index.append((waivers_failed[g][42].values == ': None, ').copy())
    waivers_failed_drop_index.append((waivers_failed[g][42].values == ': {').copy())
    g+=1

# doing the same thing for drop or no drop of player

t = 0
while t in range(16):
    waivers_failed_nodrop.append(pd.DataFrame(waivers_failed[t].values[waivers_failed_nodrop_index[t]], waivers_failed[t].index[waivers_failed_nodrop_index[t]], waivers_failed[t].columns))
    waivers_failed_drop.append(pd.DataFrame(waivers_failed[t].values[waivers_failed_drop_index[t]], waivers_failed[t].index[waivers_failed_drop_index[t]], waivers_failed[t].columns))
    waivers_failed_nodrop[t].insert(42, "a", np.nan)
    waivers_failed_nodrop[t].insert(42, "b", np.nan)
    waivers_failed_nodrop[t].columns = range(waivers_failed_nodrop[t].columns.size)
    t+=1

# doing the same thing for drop or no drop of player

if len(waivers_failed) == len(waivers_failed_nodrop):
    for i in range(len(waivers_failed)):
        waivers_failed[i].update(waivers_failed_nodrop[i])

# repeat for successful waivers

waivers_success_priority_index = []
waivers_success_priority = []

waivers_success_nopriority_index = []
waivers_success_nopriority = []

w = 0
while w in range(16):
    waivers_success_priority_index.append((waivers_success[w][19].values == 'priority').copy())
    waivers_success_nopriority_index.append((waivers_success[w][19].values == 'seq').copy())
    w+=1

h = 0
while h in range(16):
    waivers_success_priority.append(pd.DataFrame(waivers_success[h].values[waivers_success_priority_index[h]], waivers_success[h].index[waivers_success_priority_index[h]], waivers_success[h].columns))
    waivers_success_nopriority.append(pd.DataFrame(waivers_success[h].values[waivers_success_nopriority_index[h]], waivers_success[h].index[waivers_success_nopriority_index[h]], waivers_success[h].columns))
    waivers_success_nopriority[h].insert(19, "a", np.nan)
    waivers_success_nopriority[h].insert(19, "b", np.nan)
    waivers_success_nopriority[h].columns = range(waivers_success_nopriority[h].columns.size)
    h+=1

if len(waivers_success) == len(waivers_success_nopriority):
    for i in range(len(waivers_success)):
        waivers_success[i].update(waivers_success_nopriority[i])

waivers_success_nodrop_index = []
waivers_success_nodrop = []

waivers_success_drop_index = []
waivers_success_drop = []

r = 0
while r in range(16):
    waivers_success_nodrop_index.append((waivers_success[r][42].values == ': None, ').copy())
    waivers_success_drop_index.append((waivers_success[r][42].values == ': {').copy())
    r+=1

z = 0
while z in range(16):
    waivers_success_nodrop.append(pd.DataFrame(waivers_success[z].values[waivers_success_nodrop_index[z]], waivers_success[z].index[waivers_success_nodrop_index[z]], waivers_success[z].columns))
    waivers_success_drop.append(pd.DataFrame(waivers_success[z].values[waivers_success_drop_index[z]], waivers_success[z].index[waivers_success_drop_index[z]], waivers_success[z].columns))
    waivers_success_nodrop[z].insert(42, "a", np.nan)
    waivers_success_nodrop[z].insert(42, "b", np.nan)
    waivers_success_nodrop[z].columns = range(waivers_success_nodrop[z].columns.size)
    z+=1

if len(waivers_success) == len(waivers_success_nodrop):
    for i in range(len(waivers_success)):
        waivers_success[i].update(waivers_success_nodrop[i])

if len(waiver_adds) == len(waivers_success):
    for i in range(len(waiver_adds)):
        waiver_adds[i].update(waivers_success[i])
        
if len(waiver_adds) == len(waivers_failed):
    for i in range(len(waiver_adds)):
        waiver_adds[i].update(waivers_failed[i])

# for some reason successful no drops are not fixed up to this point, this fixes the discrepancy

waivers_fixer_index = []
waivers_fixer = []

r = 0
while r in range(16):
    waivers_fixer_index.append((waiver_adds[r][40].values == ': None, ').copy())
    r+=1

z = 0
while z in range(16):
    waivers_fixer.append(pd.DataFrame(waiver_adds[z].values[waivers_fixer_index[z]], waiver_adds[z].index[waivers_fixer_index[z]], waiver_adds[z].columns))
    waivers_fixer[z].insert(40, "a", np.nan)
    waivers_fixer[z].insert(40,"b",np.nan)
    waivers_fixer[z].columns = range(waivers_fixer[z].columns.size)
    z+=1

if len(waiver_adds) == len(waivers_fixer):
    for i in range(len(waiver_adds)):
        waiver_adds[i].update(waivers_fixer[i])

# Fixing first column index conventions bug

waivers_creator_bug_index = []
waivers_creator_bug = []

r = 0
while r in range(16):
    waivers_creator_bug_index.append((waiver_adds[r][25].values == 'creator').copy())
    r+=1

new_names = [30.5,30.6,30.7,30.8]
old_names = [25,26,27,28]

d = 0
while d in range(16):
    waivers_creator_bug.append(pd.DataFrame(waiver_adds[d].values[waivers_creator_bug_index[d]], waiver_adds[d].index[waivers_creator_bug_index[d]], waiver_adds[d].columns))
    waivers_creator_bug[d].rename(columns=dict(zip(old_names, new_names)), inplace=True)
    waivers_creator_bug[d] = waivers_creator_bug[d].reindex(sorted(waivers_creator_bug[d].columns), axis=1)
    d+=1

for d in range(16):
    waivers_creator_bug[d].columns = range(waivers_creator_bug[d].columns.size)

if len(waiver_adds) == len(waivers_creator_bug):
    for i in range(len(waiver_adds)):
        waiver_adds[i].update(waivers_creator_bug[i])

# Second column bug fix

waivers_consenterids_bug_index = []
waivers_consenterids_bug = []

x = 0
while x in range(16):
    waivers_consenterids_bug_index.append((waiver_adds[x][39].values == 'consenter_ids').copy())
    x+=1

new_names = [44.5,44.6]
old_names = [39,40]

d = 0
while d in range(16):
    waivers_consenterids_bug.append(pd.DataFrame(waiver_adds[d].values[waivers_consenterids_bug_index[d]], waiver_adds[d].index[waivers_consenterids_bug_index[d]], waiver_adds[d].columns))
    waivers_consenterids_bug[d].rename(columns=dict(zip(old_names, new_names)), inplace=True)
    waivers_consenterids_bug[d] = waivers_consenterids_bug[d].reindex(sorted(waivers_consenterids_bug[d].columns), axis=1)
    d+=1

# ONLY CHANGE THE ONES THAT HAVE THE BUG


for d in range(16):
    waivers_consenterids_bug[d].columns = range(waivers_consenterids_bug[d].columns.size)

if len(waiver_adds) == len(waivers_consenterids_bug):
    for i in range(len(waiver_adds)):
        waiver_adds[i].update(waivers_consenterids_bug[i])

# COPY TO ISOLATE THESE CHANGES FROM ALL WAIVERS
waiver_adds2 = waiver_adds.copy()

In [1084]:
# Concatenate ALL WEEKS
all_waivers = pd.concat(waiver_adds2,axis=0,join='inner')
old_names_waivers = [3,7,13,16,20,22,24,29,33,37,41,48]
new_names_waivers = ['Status', 'Type','Notes','Created','Priority','Sequence','Week','Team','Transaction ID','Add','Drop','Status Updated']
all_waivers.rename(columns=dict(zip(old_names_waivers, new_names_waivers)), inplace=True)

preferred_order = ['Week','Status Updated','Type','Status','Notes','Sequence','Priority', 'Created','Team','Add','Drop','Transaction ID']
avoid_notes_team = ['Week','Status Updated','Type','Status','Sequence','Priority', 'Created','Add','Drop','Transaction ID']

clean_waivers = all_waivers[preferred_order].copy()
clean_waivers.replace({'Drop': {'consenter_ids':np.nan}},inplace=True)
clean_waivers.replace({'Drop': {'roster_ids':np.nan}},inplace=True)
clean_waivers['Team'] = clean_waivers['Team'].astype(float)
clean_waivers.replace({'Team': {1130199303684915200:'manu1016',
  1150198110141026304:'alejandrovargas3000',
  1130319313522704384:'profeceltic',
  1130211805168689152:'mtamayo21',
  1130203918862192640:'frrankthetank',
  1125596889426063360:'thejahater',
  1104293144230813696:'badillad03',
  1130210372142706688:'mmonge2',
  976970448661524480:'miquev',
  1130428971469991936:'sebasvindas'}},inplace=True)

for i in avoid_notes_team:
    clean_waivers[i] = clean_waivers[i].astype(str).str.replace(",", '')
    clean_waivers[i] = clean_waivers[i].astype(str).str.replace(":", '')
    clean_waivers[i] = clean_waivers[i].astype(str).str.replace("}", '')

clean_waivers['Sequence'] = clean_waivers['Sequence'].astype(int)
clean_waivers['Priority'] = clean_waivers['Priority'].astype(int)

In [1086]:
# Separating the three types of nontrades from one another
commissioner_moves_index = []
commissioner_moves = []

# Creates indexes for first 16 weeks, for loop doesnt work because it gives a python index error
i = 0
while i in range(17):
    commissioner_moves_index.append((nontrades[i][7].values == 'commissioner').copy())
    i+=1

# Creates dataframes for first 16 weeks, for loop doesnt work because it gives a python index error
k = 0
while k in range(17):
    commissioner_moves.append(pd.DataFrame(nontrades[k].values[commissioner_moves_index[k]], nontrades[k].index[commissioner_moves_index[k]], nontrades[k].columns))
    k+=1

commissioner_moves2 = commissioner_moves.copy()

In [1088]:
# Only for Commissioner Adds/Drops. Did not have any commissioner trades this year

all_commissioner = pd.concat(commissioner_moves2,axis=0,join='inner')
old_names_commissioner = [3,7,12,13,14,15,16,25,29,33,36,38]
new_names_commissioner = ['Status', 'Type','Created','Priority','Notes','Sequence','Week','Transaction ID','Add','Drop','Team','Status Updated']
all_commissioner.rename(columns=dict(zip(old_names_commissioner, new_names_commissioner)), inplace=True)

preferred_order = ['Week','Status Updated','Type','Status','Notes','Sequence','Priority', 'Created','Team','Add','Drop','Transaction ID']

clean_commissioner = all_commissioner[preferred_order].copy()
clean_commissioner.replace({'Add': {'consenter_ids':np.nan}},inplace=True)
clean_commissioner.replace({'Drop': {'drops':np.nan}},inplace=True)
clean_commissioner.replace({'Sequence': {'leg':np.nan}},inplace=True)
clean_commissioner.replace({'Priority': {'settings':np.nan}},inplace=True)

# No se excluye a Team y Notes porque se ocupan limpiar
for i in preferred_order:
    clean_commissioner[i] = clean_commissioner[i].astype(str).str.replace(",", '')
    clean_commissioner[i] = clean_commissioner[i].astype(str).str.replace(":", '')
    clean_commissioner[i] = clean_commissioner[i].astype(str).str.replace("}", '')
    clean_commissioner[i] = clean_commissioner[i].astype(str).str.replace("[", '')
    clean_commissioner[i] = clean_commissioner[i].astype(str).str.replace("]", '')

users3 = ['manu1016','alejandrovargas3000', 'profeceltic', 'mtamayo21', 'frrankthetank', 'thejahater' , 'badillad03', 'mmonge2', 'miquev','sebasvindas']
users4 = [1130199303684915200, 1150198110141026304, 1130319313522704384, 1130211805168689152, 1130203918862192640, 1125596889426063360, 1104293144230813696, 1130210372142706688, 976970448661524480, 1130428971469991936]
users5 = [1,9,8,7,4,5,2,6,3,10]

clean_commissioner['Team'] = clean_commissioner['Team'].astype(float)

for i in range(10):
    clean_commissioner.replace({'Team': {users5[i]:users3[i]}},inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5460\1585365290.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  clean_commissioner.replace({'Sequence': {'leg':np.nan}},inplace=True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5460\1585365290.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  clean_commissioner.replace({'Priority': {'settings':np.nan}},inplace=True)

In [1090]:
# Separating the three types of nontrades from one another
free_agent_adds_index = []
free_agent_adds = []

# Creates indexes for first 16 weeks, for loop doesnt work because it gives a python index error
i = 0
while i in range(17):
    free_agent_adds_index.append((nontrades[i][7].values == 'free_agent').copy())
    i+=1

# Creates dataframes for first 16 weeks, for loop doesnt work because it gives a python index error
k = 0
while k in range(17):
    free_agent_adds.append(pd.DataFrame(nontrades[k].values[free_agent_adds_index[k]], nontrades[k].index[free_agent_adds_index[k]], nontrades[k].columns))
    k+=1

# Second column bug fix

free_agent_draft_pick_bug_index = []
free_agent_draft_pick_bug = []

x = 0
while x in range(17):
    free_agent_draft_pick_bug_index.append((free_agent_adds[x][17].values == 'draft_picks').copy())
    x+=1

new_names = [22.5,22.6]
old_names = [17,18]

d = 0
while d in range(17):
    free_agent_draft_pick_bug.append(pd.DataFrame(free_agent_adds[d].values[free_agent_draft_pick_bug_index[d]], free_agent_adds[d].index[free_agent_draft_pick_bug_index[d]], free_agent_adds[d].columns))
    free_agent_draft_pick_bug[d].rename(columns=dict(zip(old_names, new_names)), inplace=True)
    free_agent_draft_pick_bug[d] = free_agent_draft_pick_bug[d].reindex(sorted(free_agent_draft_pick_bug[d].columns), axis=1)
    d+=1

# ONLY CHANGE THE ONES THAT HAVE THE BUG


for d in range(17):
    free_agent_draft_pick_bug[d].columns = range(free_agent_draft_pick_bug[d].columns.size)

if len(free_agent_adds) == len(free_agent_draft_pick_bug):
    for i in range(len(free_agent_adds)):
        free_agent_adds[i].update(free_agent_draft_pick_bug[i])

fa_only_drop_fixer_index = []
fa_only_drop_fixer = []

r = 0
while r in range(17):
    fa_only_drop_fixer_index.append((free_agent_adds[r][28].values == ': None, ').copy())
    r+=1

z = 0
while z in range(17):
    fa_only_drop_fixer.append(pd.DataFrame(free_agent_adds[z].values[fa_only_drop_fixer_index[z]], free_agent_adds[z].index[fa_only_drop_fixer_index[z]], free_agent_adds[z].columns))
    fa_only_drop_fixer[z].insert(28, "a", np.nan)
    fa_only_drop_fixer[z].insert(28,"b",np.nan)
    fa_only_drop_fixer[z].columns = range(fa_only_drop_fixer[z].columns.size)
    z+=1

if len(free_agent_adds) == len(fa_only_drop_fixer):
    for i in range(len(free_agent_adds)):
        free_agent_adds[i].update(fa_only_drop_fixer[i])

fa_only_add_fixer_index = []
fa_only_add_fixer = []

r = 0
while r in range(17):
    fa_only_add_fixer_index.append((free_agent_adds[r][34].values == ': None, ').copy())
    r+=1

z = 0
while z in range(17):
    fa_only_add_fixer.append(pd.DataFrame(free_agent_adds[z].values[fa_only_add_fixer_index[z]], free_agent_adds[z].index[fa_only_add_fixer_index[z]], free_agent_adds[z].columns))
    fa_only_add_fixer[z].insert(34, "a", np.nan)
    fa_only_add_fixer[z].insert(34,"b",np.nan)
    fa_only_add_fixer[z].columns = range(fa_only_add_fixer[z].columns.size)
    z+=1

if len(free_agent_adds) == len(fa_only_add_fixer):
    for i in range(len(free_agent_adds)):
        free_agent_adds[i].update(fa_only_add_fixer[i])

fa_add_fixer_index = []
fa_add_fixer = []

r = 0
while r in range(17):
    fa_add_fixer_index.append((free_agent_adds[r][32].values == ': None, ').copy())
    r+=1

z = 0
while z in range(17):
    fa_add_fixer.append(pd.DataFrame(free_agent_adds[z].values[fa_add_fixer_index[z]], free_agent_adds[z].index[fa_add_fixer_index[z]], free_agent_adds[z].columns))
    fa_add_fixer[z].insert(32, "a", np.nan)
    fa_add_fixer[z].insert(32,"b",np.nan)
    fa_add_fixer[z].columns = range(fa_add_fixer[z].columns.size)
    z+=1

if len(free_agent_adds) == len(fa_add_fixer):
    for i in range(len(free_agent_adds)):
        free_agent_adds[i].update(fa_add_fixer[i])

free_agent_consenterids_bug_fixer_index = []
free_agent_consenterids_bug_fixer = []

r = 0
while r in range(17):
    free_agent_consenterids_bug_fixer_index.append((free_agent_adds[r][35].values == 'consenter_ids').copy())
    r+=1

new_names = [30.5,30.6]
old_names = [35,36]

d = 0
while d in range(17):
    free_agent_consenterids_bug_fixer.append(pd.DataFrame(free_agent_adds[d].values[free_agent_consenterids_bug_fixer_index[d]], free_agent_adds[d].index[free_agent_consenterids_bug_fixer_index[d]], free_agent_adds[d].columns))
    free_agent_consenterids_bug_fixer[d].rename(columns=dict(zip(old_names, new_names)), inplace=True)
    free_agent_consenterids_bug_fixer[d] = free_agent_consenterids_bug_fixer[d].reindex(sorted(free_agent_consenterids_bug_fixer[d].columns), axis=1)
    d+=1

# ONLY CHANGE THE ONES THAT HAVE THE BUG


for d in range(17):
    free_agent_consenterids_bug_fixer[d].columns = range(free_agent_consenterids_bug_fixer[d].columns.size)

if len(free_agent_adds) == len(free_agent_consenterids_bug_fixer):
    for i in range(len(free_agent_adds)):
        free_agent_adds[i].update(free_agent_consenterids_bug_fixer[i])

free_agent_adds2 = free_agent_adds.copy()

In [1092]:
# NOT READY YET, THERE IS A BUG LIKE WAIVERS!!!!!!!!!!!!!!!!

all_free_agent_adds = pd.concat(free_agent_adds2,axis=0,join='inner')
old_names_free_agent_adds = [3,7,12,13,14,15,16,19,25,29,35,40]
new_names_free_agent_adds = ['Status', 'Type','Created','Priority','Notes','Sequence','Week','Team','Transaction ID','Add','Drop','Status Updated']
all_free_agent_adds.rename(columns=dict(zip(old_names_free_agent_adds, new_names_free_agent_adds)), inplace=True)

preferred_order = ['Week','Status Updated','Type','Status','Notes','Sequence','Priority', 'Created','Team','Add','Drop','Transaction ID']

clean_free_agent_adds = all_free_agent_adds[preferred_order].copy()
clean_free_agent_adds.replace({'Add': {'consenter_ids':np.nan}},inplace=True)
clean_free_agent_adds.replace({'Drop': {'roster_ids':np.nan}},inplace=True)
clean_free_agent_adds.replace({'Drop': {'consenter_ids':np.nan}},inplace=True)
clean_free_agent_adds.replace({'Sequence': {'leg':np.nan}},inplace=True)
clean_free_agent_adds.replace({'Priority': {'settings':np.nan}},inplace=True)
clean_free_agent_adds['Team'] = clean_free_agent_adds['Team'].astype(float)
clean_free_agent_adds.replace({'Team': {1130199303684915200:'manu1016',
  1150198110141026304:'alejandrovargas3000',
  1130319313522704384:'profeceltic',
  1130211805168689152:'mtamayo21',
  1130203918862192640:'frrankthetank',
  1125596889426063360:'thejahater',
  1104293144230813696:'badillad03',
  1130210372142706688:'mmonge2',
  976970448661524480:'miquev',
  1130428971469991936:'sebasvindas'}},inplace=True)

avoid_team = ['Week','Status Updated','Type','Status','Sequence','Priority', 'Created','Add','Drop','Transaction ID','Notes']

# No se excluye a Notes porque se ocupa limpiar
for i in avoid_team:
    clean_free_agent_adds[i] = clean_free_agent_adds[i].astype(str).str.replace(",", '')
    clean_free_agent_adds[i] = clean_free_agent_adds[i].astype(str).str.replace(":", '')
    clean_free_agent_adds[i] = clean_free_agent_adds[i].astype(str).str.replace("}", '')
    clean_free_agent_adds[i] = clean_free_agent_adds[i].astype(str).str.replace("[", '')
    clean_free_agent_adds[i] = clean_free_agent_adds[i].astype(str).str.replace("]", '')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5460\2856862202.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  clean_free_agent_adds.replace({'Sequence': {'leg':np.nan}},inplace=True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5460\2856862202.py:15: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  clean_free_agent_adds.replace({'Priority': {'settings':np.nan}},inplace=True)

In [1094]:
clean_waivers2 = clean_waivers.copy()
clean_commissioner2 = clean_commissioner.copy()
clean_free_agent_adds2 = clean_free_agent_adds.copy()

In [1100]:
pd.set_option('display.precision', 13)
df_new = pd.concat([clean_waivers2, clean_commissioner2,clean_free_agent_adds2], axis=0)
df_new['Week'] = df_new['Week'].astype(int)
df_new['Status Updated'] = df_new['Status Updated'].astype(float)
df_new.sort_values(['Week','Status Updated','Sequence'],ascending=True,inplace=True)
df_new = df_new.reset_index(drop=True)

df_new['Created'] = pd.to_datetime(df_new['Created'], unit='ms')
df_new['Created'] = df_new['Created'] - pd.Timedelta(hours=6)
df_new['Status Updated'] = pd.to_datetime(df_new['Status Updated'], unit='ms')
df_new['Status Updated'] = df_new['Status Updated'] - pd.Timedelta(hours=6)

players2 = players.copy()
players2.reset_index(inplace=True)
# Creating a mapping of 'index' to 'full_name' using the players2 DataFrame
index_to_full_name_map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
# Making a copy of the original 'Add' column to use as a fallback for non-matching entries
original_add_column = df_new['Add'].copy()
# Mapping the 'Add' column in df_new to 'full_name'
df_new['Add'] = df_new['Add'].map(index_to_full_name_map)
# Use the original 'Add' values where the map returned NaN
df_new['Add'] = df_new['Add'].fillna(original_add_column)

index_to_fulldrop_name_map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
original_drop_column = df_new['Drop'].copy()
df_new['Drop'] = df_new['Drop'].map(index_to_fulldrop_name_map)
df_new['Drop'] = df_new['Drop'].fillna(original_drop_column)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5460\3823934418.py:8: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df_new['Created'] = pd.to_datetime(df_new['Created'], unit='ms')

In [1109]:
# df_new.to_excel("Waivers_Redraft_2025.xlsx",index=False)

In [1413]:
# Separating the three types of nontrades from one another
trades_index = []
trades = []

# Creates indexes for first 16 weeks, for loop doesnt work because it gives a python index error
i = 0
while i in range(17):
    trades_index.append((nontrades[i][7].values == 'trade').copy())
    i+=1

# Creates dataframes for first 16 weeks, for loop doesnt work because it gives a python index error
k = 0
while k in range(17):
    trades.append(pd.DataFrame(nontrades[k].values[trades_index[k]], nontrades[k].index[trades_index[k]], nontrades[k].columns))
    k+=1

for df in trades:
    df.columns = pd.io.common.dedup_names(df.columns, is_potential_multiindex=False)

all_trades = pd.concat(trades,axis=0,ignore_index=True)

In [1235]:
all_trades[all_trades.columns[0:10]]

   0       1   2         3   4     5   6      7   8         9
0  {  status  :   complete  ,   type  :   trade  ,   metadata
1  {  status  :   complete  ,   type  :   trade  ,   metadata
2  {  status  :   complete  ,   type  :   trade  ,   metadata
3  {  status  :   complete  ,   type  :   trade  ,   metadata
4  {  status  :   complete  ,   type  :   trade  ,   metadata
5  {  status  :   complete  ,   type  :   trade  ,   metadata
6  {  status  :   complete  ,   type  :   trade  ,   metadata
7  {  status  :   complete  ,   type  :   trade  ,   metadata
8  {  status  :   complete  ,   type  :   trade  ,   metadata

In [1236]:
all_trades[all_trades.columns[10:30]]

,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
0,: {,poll_id,:,1273746923769065472,",",veto_msg_id,:,1273746923857121280,"},",created,": 1758047433811,",settings,": None,",leg,": 2,",draft_picks,": [],",creator,:,1130210372142706688
1,: {,poll_id,:,1275320216875724801,",",veto_msg_id,:,1275320216947019776,"},",created,": 1758422246659,",settings,": None,",leg,": 3,",draft_picks,": [],",creator,:,1130199303684915200
2,: {,poll_id,:,1274503306479144960,",",veto_msg_id,:,1274503306575609856,"},",created,": 1758227692561,",settings,": None,",leg,": 3,",draft_picks,": [],",creator,:,1130199303684915200
3,: {,poll_id,:,1279601659386826752,",",veto_msg_id,:,1279601659437142016,"},",created,": 1759442108528,",settings,": None,",leg,": 5,",draft_picks,": [],",creator,:,1130199303684915200
4,: {,poll_id,:,1285421643769860096,",",veto_msg_id,:,1285421643849568256,"},",created,": 1760812922056,",settings,": None,",leg,": 7,",draft_picks,": [],",creator,:,1125596889426063360
5,: {,poll_id,:,1284692572572221440,",",veto_msg_id,:,1284692572656128000,"},",created,": 1760656810049,",settings,": None,",leg,": 7,",draft_picks,": [],",creator,:,976970448661524480
6,: {,poll_id,:,1290062728051838976,",",veto_msg_id,:,1290062728139935744,"},",created,": 1761937425934,",settings,": None,",leg,": 9,",draft_picks,": [],",creator,:,976970448661524480
7,: {,poll_id,:,1289725106414698496,",",veto_msg_id,:,1289725106498596864,"},",created,": 1761856818270,",settings,: {,expires_at,": 1761883199},",leg,": 9,",draft_picks,": [],",creator
8,: {,poll_id,:,1293824736261840896,",",veto_msg_id,:,1293824736354131968,"},",created,": 1762824444510,",settings,": None,",leg,": 10,",draft_picks,": [],",creator,:,1104293144230813696

In [1237]:
all_trades[all_trades.columns[30:50]]

,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49
0,",",transaction_id,:,1273746893607809024,",",adds,: {,2216,": 6,",6797,": 6,",6813,": 7},",drops,: {,2216,": 7,",6797,": 7,",6813
1,",",transaction_id,:,1275318972635447296,",",adds,: {,12529,": 1,",5967,": 3,",7090,": 1,",8126,": 3,",8676,": 3},",consenter_ids,": [1, 3],",drops
2,",",transaction_id,:,1274502953603985408,",",adds,: {,12499,": 1,",12501,": 1,",12530,": 4},",consenter_ids,": [1, 4],",drops,: {,12499,": 4,",12501
3,",",transaction_id,:,1279596583356239872,",",adds,: {,12489,": 5,",12514,": 10,",4037,": 1,",5872,": 1,",7090,": 5,",8146,": 5,",8151
4,",",transaction_id,:,1285346192015761408,",",adds,: {,5870,": 3,",8132,": 5},",drops,: {,5870,": 5,",8132,": 3},",consenter_ids,": [3, 5],",roster_ids
5,",",transaction_id,:,1284691410804547584,",",adds,: {,11584,": 3,",11620,": 1},",drops,: {,11584,": 1,",11620,": 3},",consenter_ids,": [1, 3],",roster_ids
6,",",transaction_id,:,1290062703129292800,",",adds,: {,6130,": 1,",8122,": 3},",consenter_ids,": [1, 3],",drops,: {,6130,": 3,",8122,": 1},",roster_ids
7,:,1130199303684915200,",",transaction_id,:,1289724610085920768,",",adds,: {,8126,": 1,",9753,": 3},",consenter_ids,": [1, 3],",drops,: {,8126,": 3,",9753
8,",",transaction_id,:,1293783128690675712,",",adds,: {,11627,": 3,",11631,": 2,",12512,": 2,",5022,": 2,",7588,": 3},",consenter_ids,": [2, 3],",drops

In [1238]:
all_trades[all_trades.columns[50:70]]

,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69
0,": 6},",consenter_ids,": [6, 7],",roster_ids,": [6, 7],",status_updated,": 1758050985130,",waiver_budget,: []},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,: {,12529,": 3,",5967,": 1,",7090,": 3,",8126,": 1,",8676,": 1},",roster_ids,": [1, 3],",status_updated,": 1758423587801,",waiver_budget,: []},NaN,NaN,NaN
2,": 4,",12530,": 1},",roster_ids,": [1, 4],",status_updated,": 1758228991455,",waiver_budget,: []},None,None,None,None,None,None,None,None,NaN,NaN,NaN
3,": 10,",8228,": 10,",9756,": 10},",drops,: {,12489,": 10,",12514,": 5,",4037,": 10,",5872,": 10,",7090,": 1,",8146,": 10,",8151
4,": [3, 5],",status_updated,": 1760836434441,",waiver_budget,: []},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,": [1, 3],",status_updated,": 1760657693785,",waiver_budget,: []},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,": [1, 3],",status_updated,": 1761937626083,",waiver_budget,: []},None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,": 1},",roster_ids,": [1, 3],",status_updated,": 1761862314800,",waiver_budget,: []},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,: {,11627,": 2,",11631,": 3,",12512,": 3,",5022,": 3,",7588,": 2},",roster_ids,": [2, 3],",status_updated,": 1762835176296,",waiver_budget,: []},NaN,NaN,NaN

In [1153]:
all_trades[all_trades.columns[70:90]]

,70,71,72,73,74,75,76,77,78,79,80,81,82
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,": 1,",8228,": 5,",9756,": 1},",consenter_ids,": [1, 5, 10],",roster_ids,": [1, 5, 10],",status_updated,": 1759446241631,",waiver_budget,: []}
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1245]:
sum(all_trades.iloc[3].values == 'leg')

1

In [2189]:
settings_location = all_trades[all_trades == 'settings'].stack().index.tolist()
leg_location = all_trades[all_trades == 'leg'].stack().index.tolist()
creator_location = all_trades[all_trades == 'creator'].stack().index.tolist()
transactionid_location = all_trades[all_trades == 'transaction_id'].stack().index.tolist()
adds_location = all_trades[all_trades == 'adds'].stack().index.tolist()
drops_location = all_trades[all_trades == 'drops'].stack().index.tolist()
consenterids_location = all_trades[all_trades == 'consenter_ids'].stack().index.tolist()
status_location = all_trades[all_trades == 'status_updated'].stack().index.tolist()

location_list = [settings_location,leg_location,creator_location,transactionid_location,adds_location,drops_location,consenterids_location,status_location]
trade_words = ['settings','leg','creator','transaction_id','adds','drops','consenter_ids','status_updated']

In [2191]:
import re

pat = r"^\(\d+, "

location2_list = [[re.sub(pat, '', str(item)) for item in sublist] for sublist in location_list]
location2_list = [[re.sub(r"\)", '', item) for item in sublist] for sublist in location2_list]
location2_list = [list(map(int, sublist)) for sublist in location2_list]

In [2193]:
settings_location2 = location2_list[0].copy()
leg_location2 = location2_list[1].copy()
creator_location2 = location2_list[2].copy()
transactionid_location2 = location2_list[3].copy()
adds_location2 = location2_list[4].copy()
drops_location2 = location2_list[5].copy()
consenterids_location2 = location2_list[6].copy()
status_location2 = location2_list[7].copy()

location3_list = [settings_location2,leg_location2,creator_location2,transactionid_location2,adds_location2,drops_location2,consenterids_location2,status_location2]

actual_leg = [x+1 for x in leg_location2]
actual_creator = [x+2 for x in creator_location2]
actual_transactionid = [x+2 for x in transactionid_location2]
actual_consenterids = [x+2 for x in consenterids_location2]
actual_status = [x+1 for x in status_location2]

difference_sublist = [[max(sublist) - item for item in sublist] for sublist in location3_list]
unique = [list(dict.fromkeys(sublist)) for sublist in location3_list]
difference_unique = [list(dict.fromkeys(sublist)) for sublist in difference_sublist]

In [2195]:
import copy
fixed_unique = copy.deepcopy(unique)
for i in range(len(fixed_unique)):
    # Check if the list is not empty to avoid a ValueError with max()
    if len(fixed_unique[i])>1:
        max_value = max(fixed_unique[i])
        # remove() only removes the first occurrence of the max value
        fixed_unique[i].remove(max_value)

import itertools

appended_uniques = list(itertools.chain.from_iterable(fixed_unique))

In [2197]:
all_trades3 = all_trades.copy()

In [2199]:
location_index = []
location = []
k = 0
while k in range(len(trade_words)):
    for i in fixed_unique[k]:
        location_index.append(all_trades3[all_trades3[i] == trade_words[k]].copy())
    k+=1

for k in range(len(location_index)):
    location.append(location_index[k][location_index[k].columns[:appended_uniques[k]+1]])

In [2207]:
fixed_unique

[[21],
 [23],
 [27],
 [31],
 [35],
 [43, 49, 45, 41],
 [51, 47, 43, 41],
 [55, 63, 51, 53]]

In [2215]:
location[1]

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,{,status,:,complete,",",type,:,trade,",",metadata,...,",",veto_msg_id,:,1273746923857121280,"},",created,": 1758047433811,",settings,": None,",leg
1,{,status,:,complete,",",type,:,trade,",",metadata,...,",",veto_msg_id,:,1275320216947019776,"},",created,": 1758422246659,",settings,": None,",leg
2,{,status,:,complete,",",type,:,trade,",",metadata,...,",",veto_msg_id,:,1274503306575609856,"},",created,": 1758227692561,",settings,": None,",leg
3,{,status,:,complete,",",type,:,trade,",",metadata,...,",",veto_msg_id,:,1279601659437142016,"},",created,": 1759442108528,",settings,": None,",leg
4,{,status,:,complete,",",type,:,trade,",",metadata,...,",",veto_msg_id,:,1285421643849568256,"},",created,": 1760812922056,",settings,": None,",leg
5,{,status,:,complete,",",type,:,trade,",",metadata,...,",",veto_msg_id,:,1284692572656128000,"},",created,": 1760656810049,",settings,": None,",leg
6,{,status,:,complete,",",type,:,trade,",",metadata,...,",",veto_msg_id,:,1290062728139935744,"},",created,": 1761937425934,",settings,": None,",leg
8,{,status,:,complete,",",type,:,trade,",",metadata,...,",",veto_msg_id,:,1293824736354131968,"},",created,": 1762824444510,",settings,": None,",leg

In [2202]:
location[6]

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
1,{,status,:,complete,",",type,:,trade,",",metadata,...,": 3,",7090,": 1,",8126,": 3,",8676,": 3},",consenter_ids,": [1, 3],",drops
8,{,status,:,complete,",",type,:,trade,",",metadata,...,": 2,",12512,": 2,",5022,": 2,",7588,": 3},",consenter_ids,": [2, 3],",drops

In [1724]:
# THIS IS BUGGED THE FUCK OUT RIGHT NOW, POTENTIALLY SWITCH THE for loop positions for difference unique and unique????
all_trades2 = all_trades.copy()
k = 0

for j in range(len(location3_list)):
    for i in difference_unique[j]:
        if i == 0:
            continue
        else:
            for g in fixed_unique[j]:
                temp = int(g-0.01)
                all_trades2.insert(loc = temp, column = 'bina_' + str(g) + '_' + str(k) + '_' + str(j), value = np.nan)
                k+=1
all_trades2.columns = range(all_trades2.columns.size)
# longest_row_index = all_trades2[all_trades2.isnull().sum(axis=1) == all_trades2.isnull().sum(axis=1).min()].index
# import warnings
# with warnings.catch_warnings():
#     warnings.simplefilter(action='ignore', category=FutureWarning)
#     all_trades2.loc[longest_row_index] = all_trades.loc[longest_row_index]

In [1736]:
D = pd.DataFrame({'C0':['A','B'], 1: np.nan, 2: np.nan,'C1':[10,20]})
D

  C0   1   2  C1
0  A NaN NaN  10
1  B NaN NaN  20

In [1742]:
D.loc[:,"C0":2]

  C0   1   2
0  A NaN NaN
1  B NaN NaN

In [1744]:
unique

[[21],
 [23, 25],
 [27, 29],
 [31, 33],
 [35, 37],
 [43, 49, 45, 55, 41],
 [51, 47, 43, 75, 41],
 [55, 63, 79, 51, 53]]

In [1752]:
all_trades.loc[:,40:51]

,40,41,42,43,44,45,46,47,48,49,50,51
0,": 6,",6813,": 7},",drops,: {,2216,": 7,",6797,": 7,",6813,": 6},",consenter_ids
1,": 3,",7090,": 1,",8126,": 3,",8676,": 3},",consenter_ids,": [1, 3],",drops,: {,12529
2,": 1,",12530,": 4},",consenter_ids,": [1, 4],",drops,: {,12499,": 4,",12501,": 4,",12530
3,": 10,",4037,": 1,",5872,": 1,",7090,": 5,",8146,": 5,",8151,": 10,",8228
4,": 5},",drops,: {,5870,": 5,",8132,": 3},",consenter_ids,": [3, 5],",roster_ids,": [3, 5],",status_updated
5,": 1},",drops,: {,11584,": 1,",11620,": 3},",consenter_ids,": [1, 3],",roster_ids,": [1, 3],",status_updated
6,": 3},",consenter_ids,": [1, 3],",drops,: {,6130,": 3,",8122,": 1},",roster_ids,": [1, 3],",status_updated
7,": 1,",9753,": 3},",consenter_ids,": [1, 3],",drops,: {,8126,": 3,",9753,": 1},",roster_ids
8,": 2,",12512,": 2,",5022,": 2,",7588,": 3},",consenter_ids,": [2, 3],",drops,: {,11627

In [1748]:
all_trades.loc[:,0:21]

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,{,status,:,complete,",",type,:,trade,",",metadata,...,:,1273746923769065472,",",veto_msg_id,:,1273746923857121280,"},",created,": 1758047433811,",settings
1,{,status,:,complete,",",type,:,trade,",",metadata,...,:,1275320216875724801,",",veto_msg_id,:,1275320216947019776,"},",created,": 1758422246659,",settings
2,{,status,:,complete,",",type,:,trade,",",metadata,...,:,1274503306479144960,",",veto_msg_id,:,1274503306575609856,"},",created,": 1758227692561,",settings
3,{,status,:,complete,",",type,:,trade,",",metadata,...,:,1279601659386826752,",",veto_msg_id,:,1279601659437142016,"},",created,": 1759442108528,",settings
4,{,status,:,complete,",",type,:,trade,",",metadata,...,:,1285421643769860096,",",veto_msg_id,:,1285421643849568256,"},",created,": 1760812922056,",settings
5,{,status,:,complete,",",type,:,trade,",",metadata,...,:,1284692572572221440,",",veto_msg_id,:,1284692572656128000,"},",created,": 1760656810049,",settings
6,{,status,:,complete,",",type,:,trade,",",metadata,...,:,1290062728051838976,",",veto_msg_id,:,1290062728139935744,"},",created,": 1761937425934,",settings
7,{,status,:,complete,",",type,:,trade,",",metadata,...,:,1289725106414698496,",",veto_msg_id,:,1289725106498596864,"},",created,": 1761856818270,",settings
8,{,status,:,complete,",",type,:,trade,",",metadata,...,:,1293824736261840896,",",veto_msg_id,:,1293824736354131968,"},",created,": 1762824444510,",settings

In [1728]:
all_trades2[all_trades2.columns[15:35]]

,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34
0,veto_msg_id,:,1273746923857121280,"},",created,": 1758047433811,",settings,NaN,": None,",leg,": 2,",NaN,draft_picks,": [],",creator,NaN,:,1130210372142706688,",",NaN
1,veto_msg_id,:,1275320216947019776,"},",created,": 1758422246659,",settings,NaN,": None,",leg,": 3,",NaN,draft_picks,": [],",creator,NaN,:,1130199303684915200,",",NaN
2,veto_msg_id,:,1274503306575609856,"},",created,": 1758227692561,",settings,NaN,": None,",leg,": 3,",NaN,draft_picks,": [],",creator,NaN,:,1130199303684915200,",",NaN
3,veto_msg_id,:,1279601659437142016,"},",created,": 1759442108528,",settings,NaN,": None,",leg,": 5,",NaN,draft_picks,": [],",creator,NaN,:,1130199303684915200,",",NaN
4,veto_msg_id,:,1285421643849568256,"},",created,": 1760812922056,",settings,NaN,": None,",leg,": 7,",NaN,draft_picks,": [],",creator,NaN,:,1125596889426063360,",",NaN
5,veto_msg_id,:,1284692572656128000,"},",created,": 1760656810049,",settings,NaN,": None,",leg,": 7,",NaN,draft_picks,": [],",creator,NaN,:,976970448661524480,",",NaN
6,veto_msg_id,:,1290062728139935744,"},",created,": 1761937425934,",settings,NaN,": None,",leg,": 9,",NaN,draft_picks,": [],",creator,NaN,:,976970448661524480,",",NaN
7,veto_msg_id,:,1289725106498596864,"},",created,": 1761856818270,",settings,NaN,: {,expires_at,": 1761883199},",NaN,leg,": 9,",draft_picks,NaN,": [],",creator,:,NaN
8,veto_msg_id,:,1293824736354131968,"},",created,": 1762824444510,",settings,NaN,": None,",leg,": 10,",NaN,draft_picks,": [],",creator,NaN,:,1104293144230813696,",",NaN

In [1720]:
unique[6]

[51, 47, 43, 75, 41]

In [1721]:
fixed_unique[6]

[51, 47, 43, 41]

In [1691]:
unique[6]

[51, 47, 43, 41]

In [1646]:
all_trades2[all_trades2.columns[15:35]]

,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34
0,veto_msg_id,:,1273746923857121280,"},",created,": 1758047433811,",settings,NaN,": None,",leg,": 2,",NaN,draft_picks,": [],",creator,NaN,:,1130210372142706688,",",NaN
1,veto_msg_id,:,1275320216947019776,"},",created,": 1758422246659,",settings,NaN,": None,",leg,": 3,",NaN,draft_picks,": [],",creator,NaN,:,1130199303684915200,",",NaN
2,veto_msg_id,:,1274503306575609856,"},",created,": 1758227692561,",settings,NaN,": None,",leg,": 3,",NaN,draft_picks,": [],",creator,NaN,:,1130199303684915200,",",NaN
3,veto_msg_id,:,1279601659437142016,"},",created,": 1759442108528,",settings,": None,",leg,": 5,",draft_picks,": [],",creator,:,1130199303684915200,",",transaction_id,:,1279596583356239872,","
4,veto_msg_id,:,1285421643849568256,"},",created,": 1760812922056,",settings,NaN,": None,",leg,": 7,",NaN,draft_picks,": [],",creator,NaN,:,1125596889426063360,",",NaN
5,veto_msg_id,:,1284692572656128000,"},",created,": 1760656810049,",settings,NaN,": None,",leg,": 7,",NaN,draft_picks,": [],",creator,NaN,:,976970448661524480,",",NaN
6,veto_msg_id,:,1290062728139935744,"},",created,": 1761937425934,",settings,NaN,": None,",leg,": 9,",NaN,draft_picks,": [],",creator,NaN,:,976970448661524480,",",NaN
7,veto_msg_id,:,1289725106498596864,"},",created,": 1761856818270,",settings,NaN,: {,expires_at,": 1761883199},",NaN,leg,": 9,",draft_picks,NaN,": [],",creator,:,NaN
8,veto_msg_id,:,1293824736354131968,"},",created,": 1762824444510,",settings,NaN,": None,",leg,": 10,",NaN,draft_picks,": [],",creator,NaN,:,1104293144230813696,",",NaN

In [1658]:
all_trades2[all_trades2.columns[35:55]]

,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54
0,transaction_id,:,1273746893607809024,",",adds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,transaction_id,:,1275318972635447296,",",adds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,transaction_id,:,1274502953603985408,",",adds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,adds,: {,12489,": 5,",12514,": 10,",4037,": 1,",5872,": 1,",7090,": 5,",8146,": 5,",8151,": 10,",8228,": 10,",9756,": 10},"
4,transaction_id,:,1285346192015761408,",",adds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,transaction_id,:,1284691410804547584,",",adds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,transaction_id,:,1290062703129292800,",",adds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1130199303684915200,",",transaction_id,:,1289724610085920768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,transaction_id,:,1293783128690675712,",",adds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1666]:
all_trades2[all_trades2.columns[55:75]]

,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,drops,: {,12489,": 10,",12514,": 5,",4037,": 10,",5872,": 10,",7090,": 1,",8146,": 10,",8151,": 1,",8228,": 5,",9756,": 1},"
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1662]:
all_trades2[all_trades2.columns[75:95]]

,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94
0,NaN,NaN,NaN,: {,NaN,NaN,NaN,NaN,2216,NaN,NaN,NaN,": 6,",NaN,6797,NaN,": 6,",6813,": 7},",NaN
1,NaN,NaN,NaN,: {,NaN,NaN,NaN,NaN,12529,NaN,NaN,NaN,": 1,",NaN,5967,NaN,": 3,",7090,": 1,",NaN
2,NaN,NaN,NaN,: {,NaN,NaN,NaN,NaN,12499,NaN,NaN,NaN,": 1,",NaN,12501,NaN,": 1,",12530,": 4},",NaN
3,consenter_ids,": [1, 5, 10],",roster_ids,": [1, 5, 10],",status_updated,": 1759446241631,",waiver_budget,: []},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,: {,NaN,NaN,NaN,NaN,5870,NaN,NaN,NaN,": 3,",NaN,8132,NaN,": 5},",drops,: {,NaN
5,NaN,NaN,NaN,: {,NaN,NaN,NaN,NaN,11584,NaN,NaN,NaN,": 3,",NaN,11620,NaN,": 1},",drops,: {,NaN
6,NaN,NaN,NaN,: {,NaN,NaN,NaN,NaN,6130,NaN,NaN,NaN,": 1,",NaN,8122,NaN,": 3},",consenter_ids,": [1, 3],",NaN
7,NaN,NaN,NaN,",",NaN,NaN,NaN,NaN,adds,NaN,NaN,NaN,: {,NaN,8126,NaN,": 1,",9753,": 3},",NaN
8,NaN,NaN,NaN,: {,NaN,NaN,NaN,NaN,11627,NaN,NaN,NaN,": 3,",NaN,11631,NaN,": 2,",12512,": 2,",NaN

In [1664]:
all_trades2[all_trades2.columns[95:115]]

,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114
0,drops,: {,2216,": 7,",6797,": 7,",6813,": 6},",consenter_ids,": [6, 7],",roster_ids,": [6, 7],",status_updated,": 1758050985130,",waiver_budget,: []},NaN,NaN,NaN,NaN
1,8126,": 3,",8676,": 3},",consenter_ids,": [1, 3],",drops,: {,12529,": 3,",5967,": 1,",7090,": 3,",8126,": 1,",8676,": 1},",roster_ids,": [1, 3],"
2,consenter_ids,": [1, 4],",drops,: {,12499,": 4,",12501,": 4,",12530,": 1},",roster_ids,": [1, 4],",status_updated,": 1758228991455,",waiver_budget,: []},None,None,None,None
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5870,": 5,",8132,": 3},",consenter_ids,": [3, 5],",roster_ids,": [3, 5],",status_updated,": 1760836434441,",waiver_budget,: []},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,11584,": 1,",11620,": 3},",consenter_ids,": [1, 3],",roster_ids,": [1, 3],",status_updated,": 1760657693785,",waiver_budget,: []},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,drops,: {,6130,": 3,",8122,": 1},",roster_ids,": [1, 3],",status_updated,": 1761937626083,",waiver_budget,: []},None,None,NaN,NaN,NaN,NaN,NaN,NaN
7,consenter_ids,": [1, 3],",drops,: {,8126,": 3,",9753,": 1},",roster_ids,": [1, 3],",status_updated,": 1761862314800,",waiver_budget,: []},NaN,NaN,NaN,NaN,NaN,NaN
8,5022,": 2,",7588,": 3},",consenter_ids,": [2, 3],",drops,: {,11627,": 2,",11631,": 3,",12512,": 3,",5022,": 3,",7588,": 2},",roster_ids,": [2, 3],"

In [1486]:
difference_unique[6]

[24, 28, 32, 0, 34]

In [1487]:
unique[6]

[51, 47, 43, 75, 41]

In [1353]:
actual_leg

[24, 24, 24, 24, 24, 24, 24, 26, 24]

In [1371]:
consenterids_location2

[51, 47, 43, 75, 47, 47, 41, 43, 47]

In [4373]:
pd.options.mode.chained_assignment = None

trades = []
for i in range(15):
    trades.append(weeks[i][weeks[i][7] == 'trade'])
for i in range(15):
    trades[i].reset_index(drop=True,inplace=True)
    for j in trades[i].columns:
        trades[i][j] = trades[i][j].astype(str).str.replace(":", '')
        trades[i][j] = trades[i][j].astype(str).str.replace(",", '')
        trades[i][j] = trades[i][j].astype(str).str.replace("}", '')
        trades[i][j] = trades[i][j].astype(str).str.replace("{", '')


## week 3
a = pd.DataFrame(trades[2].iloc[0]).T.copy()
b = pd.DataFrame(trades[2].iloc[1]).T.copy()

a.insert(30,'Accepted By (B)','1130210372142706688')
a.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,21,22,25,26,28,30,31,32,34,36,38,40,42,43,44,45,46,47,48,49,50,51,52,53,54,55,57,58],inplace=True)
a.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',37:'Sends 1',39:'Sends 2',41:'Receives 1',56:'Status Updated'},axis=1,inplace=True)
a.drop(columns=[19,23,27,35],inplace=True)
a.insert(6, 'j3', a['Sends 1'])
a.insert(7, 'j1', a['Receives 1'])
a.insert(8, 'j2', a['Sends 2'])
a.drop(columns=['Sends 1','Sends 2','Receives 1'],inplace=True)
a.rename({'j1':'B Receives 1','j2':'B Receives 2','j3':'A Receives 1'},axis=1,inplace=True)

b.insert(30,'Accepted By (B)','1125596889426063360')
b.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,21,22,25,26,28,30,32,34,36,49,50,51,53,54,55,56,57,58],inplace=True)
b.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',52:'Status Updated',37:'j2',39:'j1'},axis=1,inplace=True)
b.insert(10,'A Receives 1',b['j1'])
b.insert(11,'B Receives 1',b['j2'])
b.drop(columns=[19,23,27,31,35,38,40,41,42,43,44,45,46,47,48,'j2','j1'],axis=1,inplace=True)
## week 5
c = pd.DataFrame(trades[4].iloc[0]).T.copy()
c.insert(30,'Accepted By (B)','1125596889426063360')
c.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,25,26,27,28,30,31,32,34,35],inplace=True)
c.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',60:'Status Updated'},axis=1,inplace=True)
c.drop(columns=[36,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,61,62],inplace=True)
c.insert(6,'A Receives 1',c[39])
c.insert(7,'A Receives 2',c[43])
c.insert(8,'B Receives 1',c[37])
c.insert(9,'B Receives 2',c[41])
c.drop(columns=[37,38,39,40,41,42,43,44],inplace=True)
## week 6
d = pd.DataFrame(trades[5].iloc[0]).T.copy()
d.insert(30,'Accepted By (B)','1130199303684915200')
d.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,21,22,25,26,28,30,32,34,36,49,50,51,53,54],inplace=True)
d.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',52:'Status Updated',37:'j2',39:'j1'},axis=1,inplace=True)
d.insert(10,'A Receives 1',d['j1'])
d.insert(11,'B Receives 1',d['j2'])
d.drop(columns=[19,23,27,31,35,38,40,41,42,43,44,45,46,47,48,'j2','j1'],axis=1,inplace=True)
## week 7
e = pd.DataFrame(trades[6].iloc[0]).T.copy()
e.insert(30,'Accepted By (B)','1130203918862192640')
e.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,21,22,25,26,28,30,32,34,36,49,50,51,53,54],inplace=True)
e.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',52:'Status Updated',37:'j1',39:'j2'},axis=1,inplace=True)
e.drop(columns=[19,23,27,31,35,38,40,41,42,43,44,45,46,47,48],axis=1,inplace=True)
e.insert(6,'A Receives 1',e['j1'])
e.insert(7,'B Receives 1',e['j2'])
e.drop(columns=['j1','j2'],axis=1,inplace=True)
## week 8
f = pd.DataFrame(trades[7].iloc[0]).T.copy()
g = pd.DataFrame(trades[7].iloc[1]).T.copy()

f.insert(30,'Accepted By (B)','976970448661524480')
f.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,25,26,27,28,30,31,32,34,35],inplace=True)
f.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',60:'Status Updated'},axis=1,inplace=True)
f.drop(columns=[36,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,61,62,63,64,65,66,67,68,69,70,71,72],inplace=True)
f.insert(6,'A Receives 1',f[41])
f.insert(7,'A Receives 2',f[43])
f.insert(8,'B Receives 1',f[37])
f.insert(9,'B Receives 2',f[39])
f.drop(columns=[37,38,39,40,41,42,43,44],inplace=True)

g.insert(32,'Accepted By (B)','1130428971469991936')
g.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,27,28,29,30,32,33,34],inplace=True)
g.rename({7:'Type',20:'Created',26:'Week',31:'Sent By (A)',35:'Transaction ID',70:'Status Updated'},axis=1,inplace=True)
g.drop(columns=[36,37,38],inplace=True)
g.insert(6,'A Receives 1',g[39])
g.insert(7,'A Receives 2',g[43])
g.insert(8,'A Receives 3',g[45])
g.insert(9,'B Receives 1',g[41])
g.insert(10,'B Receives 2',g[47])
g.insert(11,'B Receives 3',g[49])
g.drop(columns=[39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,71,72],inplace=True)

## week 9
h = pd.DataFrame(trades[8].iloc[0]).T.copy()

h.insert(30,'Accepted By (B)','1130359651561824256')
h.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,21,22,25,26,28,30,31,32,34,36,38,40,42,43,44,45,46,47,48,49,50,51,52,53,54],inplace=True)
h.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',56:'Status Updated'},axis=1,inplace=True)
h.drop(columns=[19,23,27,35],inplace=True)
h.insert(6, 'A Receives 1', h[37])
h.insert(7, 'B Receives 1', h[39])
h.insert(8, 'B Receives 2', h[41])
h.drop(columns=[37,39,41,55,57,58],inplace=True)

## week 10
i = pd.DataFrame(trades[9].iloc[0]).T.copy()
j = pd.DataFrame(trades[9].iloc[1]).T.copy()
k = pd.DataFrame(trades[9].iloc[2]).T.copy()
l = pd.DataFrame(trades[9].iloc[3]).T.copy()

i.insert(30,'Accepted By (B)','1130211805168689152')
i.insert(31,'Accepted By (C)','1130428971469991936')
i.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,21,22],inplace=True)
i.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',76:'Status Updated'},axis=1,inplace=True)
i.drop(columns=[19,23,25,26,27,28,30,31,32,34,35,36],inplace=True)
i.insert(7,'A Receives 1',i[39])
i.insert(8,'A Receives 2',i[47])
i.insert(9,'A Receives 3',i[49])
i.insert(10,'B Receives 1',i[37])
i.insert(11,'B Receives 2',i[41])
i.insert(12,'B Receives 3',i[45])
i.insert(13,'C Receives 1',i[43])
i.insert(14,'C Receives 2',i[51])
i.insert(15,'A Sends 1',i[37])
i.insert(16,'A Sends 2',i[45])
i.insert(17,'A Sends 3',i[43])
i.insert(18,'B Sends 1',i[47])
i.insert(19,'B Sends 2',i[51])
i.insert(20,'C Sends 1',i[39])
i.insert(21,'C Sends 2',i[49])
i.insert(22,'C Sends 3',i[41])
i.drop(columns=[37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,77,78],inplace=True)

j.insert(30,'Accepted By (B)','1104293144230813696')
j.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,21,22],inplace=True)
j.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',60:'Status Updated'},axis=1,inplace=True)
j.drop(columns=[19,23,25,26,27,28,30,31,32,34],inplace=True)
j.insert(7,'A Receives 1',j[37])
j.insert(8,'A Receives 2',j[43])
j.insert(9,'B Receives 1',j[39])
j.insert(10,'B Receives 2',j[41])
j.drop(columns=[35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78],inplace=True)

k.insert(30,'Accepted By (B)','1130210372142706688')
k.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23],inplace=True)
k.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',56:'Status Updated'},axis=1,inplace=True)
k.drop(columns=[25,26,27,28,30,31,32,34,35,36],inplace=True)
k.insert(10,'A Receives 1',k[37])
k.insert(11,'A Receives 2',k[41])
k.insert(12,'B Receives 1',k[39])
k.drop(columns=[37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78],axis=1,inplace=True)

l.insert(30,'Accepted By (B)','1130210372142706688')
l.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23],inplace=True)
l.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',56:'Status Updated'},axis=1,inplace=True)
l.drop(columns=[25,26,27,28,30,31,32,34,35,36],inplace=True)
l.insert(10,'A Receives 1',l[41])
l.insert(11,'B Receives 1',l[37])
l.insert(12,'B Receives 2',l[39])
l.drop(columns=[37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78],axis=1,inplace=True)

## week 11
m = pd.DataFrame(trades[10].iloc[0]).T.copy()

m.insert(30,'Accepted By (B)','1130199303684915200')
m.insert(31,'Accepted By (C)','976970448661524480')
m.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23],inplace=True)
m.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',80:'Status Updated'},axis=1,inplace=True)
m.drop(columns=[25,26,27,28,30,31,32],inplace=True)

m.insert(7,'A Receives 1',m[43])
m.insert(8,'A Receives 2',m[47])
m.insert(9,'A Receives 3',m[51])

m.insert(10,'B Receives 1',m[37])
m.insert(11,'B Receives 2',m[41])
m.insert(12,'B Receives 3',m[45])

m.insert(13,'C Receives 1',m[39])
m.insert(14,'C Receives 2',m[49])
m.insert(15,'C Receives 3',m[53])

m.insert(16,'A Sends 1',m[59])
m.insert(17,'A Sends 2',m[67])
m.insert(18,'A Sends 3',m[71])

m.insert(19,'B Sends 1',m[61])
m.insert(20,'B Sends 2',m[73])
m.insert(21,'B Sends 3',m[75])

m.insert(22,'C Sends 1',m[63])
m.insert(23,'C Sends 2',m[65])
m.insert(24,'C Sends 3',m[69])
m.drop(columns=[34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,81,82],inplace=True)

## week 12
n = pd.DataFrame(trades[11].iloc[0]).T.copy()
o = pd.DataFrame(trades[11].iloc[1]).T.copy()
p = pd.DataFrame(trades[11].iloc[2]).T.copy()
q = pd.DataFrame(trades[11].iloc[3]).T.copy()
r = pd.DataFrame(trades[11].iloc[4]).T.copy()

n.insert(32,'Accepted By (B)','1130359651561824256')
n.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,21,22],inplace=True)
n.rename({7:'Type',20:'Created',26:'Week',31:'Sent By (A)',35:'Transaction ID',58:'Status Updated'},axis=1,inplace=True)
n.drop(columns=[19,23,24,25,27,28,29,30,32,33,34,36,37,38,55,56,57,59,60,61,62,63,64,65,66],inplace=True)
n.insert(10,'A Receives 1',n[41])
n.insert(11,'B Receives 1',n[39])
n.insert(12,'B Receives 2',n[43])
n.drop(columns=[39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54],inplace=True)

o.insert(30,'Accepted By (B)','976970448661524480')
o.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23],inplace=True)
o.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',52:'Status Updated'},axis=1,inplace=True)
o.drop(columns=[25,26,27,28,30,31,32,34],inplace=True)
o.insert(10,'A Receives 1',o[37])
o.insert(11,'B Receives 1',o[39])
o.drop(columns=[35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,53,54,55,56,57,58,59,60,61,62,63,64,65,66],inplace=True)

p.insert(30,'Accepted By (B)','976970448661524480')
p.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23],inplace=True)
p.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',60:'Status Updated'},axis=1,inplace=True)
p.drop(columns=[25,26,27,28],inplace=True)
p.insert(10,'A Receives 1',p[37])
p.insert(11,'A Receives 2',p[41])
p.insert(12,'B Receives 1',p[39])
p.insert(13,'B Receives 2',p[43])
p.drop(columns=[30,31,32,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,61,62,63,64,65,66],inplace=True)

q.insert(30,'Accepted By (B)','1130359651561824256')
q.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23],inplace=True)
q.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',52:'Status Updated'},axis=1,inplace=True)
q.drop(columns=[25,26,27,28,30,31,32,34],inplace=True)
q.insert(10,'A Receives 1',q[39])
q.insert(11,'B Receives 1',q[37])
q.drop(columns=[35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,53,54,55,56,57,58,59,60,61,62,63,64,65,66],inplace=True)

r.insert(30,'Accepted By (B)','1130199303684915200')
r.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23],inplace=True)
r.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',64:'Status Updated'},axis=1,inplace=True)
r.drop(columns=[25,26,27,28],inplace=True)
r.insert(10,'A Receives 1',r[37])
r.insert(11,'A Receives 2',r[41])
r.insert(12,'B Receives 1',r[39])
r.insert(13,'B Receives 2',r[43])
r.insert(14,'B Receives 3',r[45])
r.drop(columns=[30,31,32,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,65,66],inplace=True)

## week 13
s = pd.DataFrame(trades[12].iloc[0]).T.copy()
t = pd.DataFrame(trades[12].iloc[1]).T.copy()
u = pd.DataFrame(trades[12].iloc[2]).T.copy()
v = pd.DataFrame(trades[12].iloc[3]).T.copy()
w = pd.DataFrame(trades[12].iloc[4]).T.copy()

s.insert(30,'Accepted By (B)','1130428971469991936')
s.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23],inplace=True)
s.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',56:'Status Updated'},axis=1,inplace=True)
s.drop(columns=[25,26,27,28],inplace=True)
s.insert(10,'A Receives 1',s[37])
s.insert(11,'B Receives 1',s[39])
s.insert(12,'B Receives 2',s[41])
s.drop(columns=[30,31,32,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,57,58],inplace=True)

t.insert(30,'Accepted By (B)','1130210372142706688')
t.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23],inplace=True)
t.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',52:'Status Updated'},axis=1,inplace=True)
t.drop(columns=[25,26,27,28],inplace=True)
t.insert(10,'A Receives 1',t[39])
t.insert(11,'B Receives 1',t[37])
t.drop(columns=[30,31,32,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,53,54,55,56,57,58],inplace=True)

u.insert(30,'Accepted By (B)','1130199303684915200')
u.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23],inplace=True)
u.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',52:'Status Updated'},axis=1,inplace=True)
u.drop(columns=[25,26,27,28],inplace=True)
u.insert(10,'A Receives 1',u[37])
u.insert(11,'B Receives 1',u[39])
u.drop(columns=[30,31,32,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,53,54,55,56,57,58],inplace=True)

v.insert(30,'Accepted By (B)','1130428971469991936')
v.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23],inplace=True)
v.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',52:'Status Updated'},axis=1,inplace=True)
v.drop(columns=[25,26,27,28],inplace=True)
v.insert(10,'A Receives 1',v[39])
v.insert(11,'B Receives 1',v[37])
v.drop(columns=[30,31,32,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,53,54,55,56,57,58],inplace=True)

w.insert(30,'Accepted By (B)','1104293144230813696')
w.drop(columns=[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23],inplace=True)
w.rename({7:'Type',20:'Created',24:'Week',29:'Sent By (A)',33:'Transaction ID',52:'Status Updated'},axis=1,inplace=True)
w.drop(columns=[25,26,27,28],inplace=True)
w.insert(10,'A Receives 1',w[39])
w.insert(11,'B Receives 1',w[37])
w.drop(columns=[30,31,32,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,53,54,55,56,57,58],inplace=True)

tradesmaster = [a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w]

In [4383]:
realtradesmaster = pd.concat(tradesmaster,axis=0,ignore_index=True)
realtradesmaster = realtradesmaster[['Type', 'Created', 'Week','Transaction ID', 'Sent By (A)', 'Accepted By (B)', 'Accepted By (C)',
                                     'A Receives 1','A Receives 2', 'A Receives 3', 'B Receives 1', 'B Receives 2', 'B Receives 3',
                                     'C Receives 1', 'C Receives 2', 'C Receives 3','A Sends 1',
                                     'A Sends 2', 'A Sends 3', 'B Sends 1', 'B Sends 2','B Sends 3', 'C Sends 1',
                                     'C Sends 2', 'C Sends 3', 'Status Updated',]]

# Creating a mapping of 'index' to 'full_name' using the players2 DataFrame
amap = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
# Making a copy of the original 'Add' column to use as a fallback for non-matching entries
a1origincol = realtradesmaster['A Receives 1'].copy()
# Mapping the 'Add' column in realwaivermaster to 'full_name'
realtradesmaster['A Receives 1'] = realtradesmaster['A Receives 1'].map(amap)
# Use the original 'Add' values where the map returned NaN
realtradesmaster['A Receives 1'] = realtradesmaster['A Receives 1'].fillna(a1origincol)

a2map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
a2origincol = realtradesmaster['A Receives 2'].copy()
realtradesmaster['A Receives 2'] = realtradesmaster['A Receives 2'].map(a2map)
realtradesmaster['A Receives 2'] = realtradesmaster['A Receives 2'].fillna(a2origincol)

a3map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
a3origincol = realtradesmaster['A Receives 3'].copy()
realtradesmaster['A Receives 3'] = realtradesmaster['A Receives 3'].map(a3map)
realtradesmaster['A Receives 3'] = realtradesmaster['A Receives 3'].fillna(a3origincol)

# Creating a mapping of 'index' to 'full_name' using the players2 DataFrame
a12map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
# Making a copy of the original 'Add' column to use as a fallback for non-matching entries
a12origincol = realtradesmaster['A Sends 1'].copy()
# Mapping the 'Add' column in realwaivermaster to 'full_name'
realtradesmaster['A Sends 1'] = realtradesmaster['A Sends 1'].map(a12map)
# Use the original 'Add' values where the map returned NaN
realtradesmaster['A Sends 1'] = realtradesmaster['A Sends 1'].fillna(a12origincol)

a22map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
a22origincol = realtradesmaster['A Sends 2'].copy()
realtradesmaster['A Sends 2'] = realtradesmaster['A Sends 2'].map(a22map)
realtradesmaster['A Sends 2'] = realtradesmaster['A Sends 2'].fillna(a22origincol)

a32map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
a32origincol = realtradesmaster['A Sends 3'].copy()
realtradesmaster['A Sends 3'] = realtradesmaster['A Sends 3'].map(a32map)
realtradesmaster['A Sends 3'] = realtradesmaster['A Sends 3'].fillna(a32origincol)

# Creating a mapping of 'index' to 'full_name' using the players2 DataFrame
bmap = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
# Making a copy of the original 'Add' column to use as a fallback for non-matching entries
b1origincol = realtradesmaster['B Receives 1'].copy()
# Mapping the 'Add' column in realwaivermaster to 'full_name'
realtradesmaster['B Receives 1'] = realtradesmaster['B Receives 1'].map(bmap)
# Use the original 'Add' values where the map returned NaN
realtradesmaster['B Receives 1'] = realtradesmaster['B Receives 1'].fillna(b1origincol)

b2map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
b2origincol = realtradesmaster['B Receives 2'].copy()
realtradesmaster['B Receives 2'] = realtradesmaster['B Receives 2'].map(b2map)
realtradesmaster['B Receives 2'] = realtradesmaster['B Receives 2'].fillna(b2origincol)

b3map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
b3origincol = realtradesmaster['B Receives 3'].copy()
realtradesmaster['B Receives 3'] = realtradesmaster['B Receives 3'].map(b3map)
realtradesmaster['B Receives 3'] = realtradesmaster['B Receives 3'].fillna(b3origincol)

# Creating a mapping of 'index' to 'full_name' using the players2 DataFrame
b12map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
# Making a copy of the original 'Add' column to use as a fallback for non-matching entries
b12origincol = realtradesmaster['B Sends 1'].copy()
# Mapping the 'Add' column in realwaivermaster to 'full_name'
realtradesmaster['B Sends 1'] = realtradesmaster['B Sends 1'].map(b12map)
# Use the original 'Add' values where the map returned NaN
realtradesmaster['B Sends 1'] = realtradesmaster['B Sends 1'].fillna(b12origincol)

b22map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
b22origincol = realtradesmaster['B Sends 2'].copy()
realtradesmaster['B Sends 2'] = realtradesmaster['B Sends 2'].map(b22map)
realtradesmaster['B Sends 2'] = realtradesmaster['B Sends 2'].fillna(b22origincol)

b32map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
b32origincol = realtradesmaster['B Sends 3'].copy()
realtradesmaster['B Sends 3'] = realtradesmaster['B Sends 3'].map(b32map)
realtradesmaster['B Sends 3'] = realtradesmaster['B Sends 3'].fillna(b32origincol)

# Creating a mapping of 'index' to 'full_name' using the players2 DataFrame
cmap = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
# Making a copy of the original 'Add' column to use as a fallback for non-matching entries
c1origincol = realtradesmaster['C Receives 1'].copy()
# Mapping the 'Add' column in realwaivermaster to 'full_name'
realtradesmaster['C Receives 1'] = realtradesmaster['C Receives 1'].map(cmap)
# Use the original 'Add' values where the map returned NaN
realtradesmaster['C Receives 1'] = realtradesmaster['C Receives 1'].fillna(c1origincol)

c2map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
c2origincol = realtradesmaster['C Receives 2'].copy()
realtradesmaster['C Receives 2'] = realtradesmaster['C Receives 2'].map(c2map)
realtradesmaster['C Receives 2'] = realtradesmaster['C Receives 2'].fillna(c2origincol)

c3map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
c3origincol = realtradesmaster['C Receives 3'].copy()
realtradesmaster['C Receives 3'] = realtradesmaster['C Receives 3'].map(c3map)
realtradesmaster['C Receives 3'] = realtradesmaster['C Receives 3'].fillna(c3origincol)

# Creating a mapping of 'index' to 'full_name' using the players2 DataFrame
c12map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
# Making a copy of the original 'Add' column to use as a fallback for non-matching entries
c12origincol = realtradesmaster['C Sends 1'].copy()
# Mapping the 'Add' column in realwaivermaster to 'full_name'
realtradesmaster['C Sends 1'] = realtradesmaster['C Sends 1'].map(c12map)
# Use the original 'Add' values where the map returned NaN
realtradesmaster['C Sends 1'] = realtradesmaster['C Sends 1'].fillna(c12origincol)

c22map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
c22origincol = realtradesmaster['C Sends 2'].copy()
realtradesmaster['C Sends 2'] = realtradesmaster['C Sends 2'].map(c22map)
realtradesmaster['C Sends 2'] = realtradesmaster['C Sends 2'].fillna(c22origincol)

c32map = pd.Series(players2['full_name'].values, index=players2['index']).to_dict()
c32origincol = realtradesmaster['C Sends 3'].copy()
realtradesmaster['C Sends 3'] = realtradesmaster['C Sends 3'].map(c32map)
realtradesmaster['C Sends 3'] = realtradesmaster['C Sends 3'].fillna(c32origincol)

users3 = ['manu1016','ggarita34', 'profeceltic', 'mtamayo21', 'frrankthetank', 'thejahater' , 'badillad03', 'mmonge2', 'miquev','sebasvindas']
users4 = [1130199303684915200, 1130359651561824256, 1130319313522704384, 1130211805168689152, 1130203918862192640, 1125596889426063360, 1104293144230813696, 1130210372142706688, 976970448661524480, 1130428971469991936]
users5 = [1,9,8,7,4,5,2,6,3,10]

realtradesmaster['Sent By (A)'] = realtradesmaster['Sent By (A)'].astype(float).copy()
realtradesmaster['Accepted By (B)'] = realtradesmaster['Accepted By (B)'].astype(float).copy()
realtradesmaster['Accepted By (C)'] = realtradesmaster['Accepted By (C)'].astype(float).copy()

# Creating the dictionary from the lists
replace_users = dict(zip(users4, users3))
# If you want to replace values in multiple columns, simply apply the replace method without specifying the column
realtradesmaster = realtradesmaster.replace(replace_users)

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

realtradesmaster['Created'] = pd.to_datetime(realtradesmaster['Created'], unit='ms')
realtradesmaster['Created'] = realtradesmaster['Created'] - pd.Timedelta(hours=6)
realtradesmaster['Status Updated'] = pd.to_datetime(realtradesmaster['Status Updated'], unit='ms')
realtradesmaster['Status Updated'] = realtradesmaster['Status Updated'] - pd.Timedelta(hours=6)
realtradesmaster.sort_values(['Created'],inplace=True)
realtradesmaster.reset_index(drop=True,inplace=True)

In [4385]:
realtradesmaster[realtradesmaster.columns[0:]]

,Type,Created,Week,Transaction ID,Sent By (A),Accepted By (B),Accepted By (C),A Receives 1,A Receives 2,A Receives 3,...,A Sends 1,A Sends 2,A Sends 3,B Sends 1,B Sends 2,B Sends 3,C Sends 1,C Sends 2,C Sends 3,Status Updated
0,trade,2024-09-18 21:50:55.650,3,1142341118609346560,mmonge2,thejahater,NaN,Antonio Gibson,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-19 08:11:13.833
1,trade,2024-09-21 18:07:42.484,3,1143372107200638976,manu1016,mmonge2,NaN,J.K. Dobbins,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-21 18:46:30.320
2,trade,2024-10-02 21:52:01.923,5,1147414826701086720,mtamayo21,thejahater,NaN,Patrick Mahomes,Jameson Williams,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-02 23:00:57.244
3,trade,2024-10-11 16:09:58.076,6,1150590234237927424,mmonge2,manu1016,NaN,Najee Harris,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-11 16:17:20.997
4,trade,2024-10-22 20:36:28.659,7,1154643570125774848,manu1016,frrankthetank,NaN,Tyrone Tracy,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-23 20:41:49.187
5,trade,2024-10-23 14:45:46.626,8,1154917701308059648,miquev,sebasvindas,NaN,Dalton Kincaid,Diontae Johnson,D'Andre Swift,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-23 15:33:57.141
6,trade,2024-10-24 18:16:59.793,8,1155333244289036288,mtamayo21,miquev,NaN,Diontae Johnson,Zay Flowers,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-24 18:22:12.405
7,trade,2024-11-03 23:28:54.567,9,1159035618397118464,mmonge2,ggarita34,NaN,Tyler Lockett,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-11-04 07:51:39.091
8,trade,2024-11-06 17:47:13.186,10,1160036792968740864,frrankthetank,mmonge2,NaN,Najee Harris,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-11-06 21:30:46.652
9,trade,2024-11-11 23:18:03.256,10,1161931989525307392,thejahater,mmonge2,NaN,Rome Odunze,Khalil Shakir,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-11-11 23:25:09.293
10,trade,2024-11-12 12:01:56.368,10,1162124227529637888,sebasvindas,badillad03,NaN,Ladd McConkey,Kenneth Walker,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-11-12 12:11:58.208
11,trade,2024-11-12 23:05:00.794,10,1162291095506739200,manu1016,mtamayo21,sebasvindas,Keenan Allen,Breece Hall,Jahmyr Gibbs,...,Bucky Irving,James Cook,Christian McCaffrey,Breece Hall,Jaxon Smith-Njigba,NaN,Keenan Allen,Jahmyr Gibbs,Amari Cooper,2024-11-12 23:11:41.382
12,trade,2024-11-13 15:19:17.894,11,1162536282355290112,badillad03,manu1016,miquev,Darnell Mooney,Garrett Wilson,De'Von Achane,...,Cedric Tillman,George Pickens,Kyren Williams,Calvin Ridley,De'Von Achane,Josh Downs,David Montgomery,Darnell Mooney,Garrett Wilson,2024-11-13 15:26:34.088
13,trade,2024-11-21 18:47:17.361,12,1165487727958990848,mtamayo21,manu1016,NaN,Tyrone Tracy,Nico Collins,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-11-21 19:12:32.951
14,trade,2024-11-23 19:35:52.019,12,1166224728651132928,sebasvindas,ggarita34,NaN,Jordan Love,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-11-24 08:26:22.339
15,trade,2024-11-25 23:42:28.852,12,1167011566799282176,mmonge2,miquev,NaN,Dalton Kincaid,Rachaad White,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-11-25 23:49:48.214
16,trade,2024-11-26 10:46:36.964,12,1167178701894098944,badillad03,miquev,NaN,Bo Nix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-11-26 11:11:27.827
17,trade,2024-11-26 18:21:17.641,12,1167293125346566144,mmonge2,ggarita34,NaN,Aaron Jones,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-11-26 21:27:10.254
18,trade,2024-12-02 17:45:48.460,13,1169458522107789312,frrankthetank,badillad03,NaN,Garrett Wilson,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-02 17:56:36.980
19,trade,2024-12-02 19:17:26.282,13,1169481581645570048,mtamayo21,sebasvindas,NaN,Jaxon Smith-Njigba,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-02 22:55:09.904
20,trade,2024-12-03 11:43:07.720,13,1169729638814322688,frrankthetank,manu1016,NaN,Devaughn Vele,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-03 12:24:55.776
21,trade,2024-12-03 12:29:16.521,13,1169741252007522304,frrankthetank,mmonge2,NaN,PHI,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-03 16:39:08.360
22,trade,2024-12-03 15:11:01.022,13,1169781955634987008,manu1016,sebasvindas,NaN,Keon Coleman,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-03 21:59:01.015

In [4301]:
players.loc['8146']

full_name                                                    Garrett Wilson
rotowire_id                                                           15829
search_last_name                                                     wilson
injury_notes                                                           None
weight                                                                  183
active                                                                 True
first_name                                                          Garrett
last_name                                                            Wilson
sportradar_id                          68d72fe0-79b2-4fdb-afd5-6c79676e77f3
practice_participation                                                 None
fantasy_data_id                                                        None
stats_id                                                               None
yahoo_id                                                               None
injury_start_date                                                      None
practice_description                                                   None
status                                                               Active
birth_city                                                             None
gsis_id                                                                None
espn_id                                                                None
search_first_name                                                   garrett
years_exp                                                                 2
injury_body_part                                                       None
team_abbr                                                              None
search_full_name                                              garrettwilson
rotoworld_id                                                           None
high_school                                                Lake Travis (TX)
metadata                  {'channel_id': '1113708743457009664', 'rookie_...
number                                                                    5
birth_date                                                       2000-07-22
team                                                                    NYJ
birth_country                                                          None
depth_chart_position                                                    LWR
hashtag                                            #garrettwilson-NFL-NYJ-5
search_rank                                                              12
sport                                                                   nfl
depth_chart_order                                                         2
injury_status                                                          None
competitions                                                             []
opta_id                                                                None
swish_id                                                            1164889
fantasy_positions                                                      [WR]
news_updated                                                  1734926151197
position                                                                 WR
height                                                                   72
pandascore_id                                                          None
birth_state                                                            None
player_id                                                              8146
team_changed_at                                                        None
college                                                          Ohio State
age                                                                      24
oddsjam_id                                                     F6B4E30BC359
Name: 8146, dtype: object

In [4389]:
# realtradesmaster.to_excel("trades.xlsx",index=False)